### ISSUE TITLE
Incorrect parsing of nested query

### ISSUE THREAD

**Issue by bquorning** [rack/rack#1086]
Trying to upgrade an app to Rails 5.0.0.rc1, I noticed a bug in Rack’s query parser. I wrote two test cases for spec_utils.rb:

```rb
# Query to hash - fails
Rack::Utils.parse_nested_query("x[][y][][z]=1&x[][y][][w]=2").
  must_equal "x" => [{ "y" => [{ "z" => "1", "w" => "2" }] }]

# Hash to query - passes
Rack::Utils.build_nested_query("x" => [{ "y" => [{ "z" => "1", "w" => "2" }] }]).
  must_equal "x[][y][][z]=1&x[][y][][w]=2"
```

It looks like both these tests would’ve passed before #1029, so there’s a starting point.

Should I open an issue on [rails/rails](https://github.com/rails/rails) too? I personally feel this might be a blocker for their v5.0.0 release.

cc/ @rthbound, @tenderlove (related to https://github.com/rails/rails/issues/23997#issuecomment-224726220 ?)

**Comment by rthbound** [comment]
@bquorning I don't think it would be appropriate to file under rails as well. What was the unexpected result from the failing assertion?

In #1029 I gathered commits from myself and two others to fix two documented bugs.

@tenderlove #1029, it sounds to me like we'll want to add the new failing test cases and then make changes that satisfy them. It seems like we're avoiding reverting #1029 because it adds test cases that should pass - that right?

**Comment by bquorning** [comment]
Yeah, I forgot to include the unexpected result of the assertion:

> ```
> Rack::Utils.parse_nested_query("x[][y][][z]=1&x[][y][][w]=2").
>   must_equal "x" => [{ "y" => [{ "z" => "1", "w" => "2" }] }]
> ```

```
--- expected
+++ actual
@@ -1 +1 @@
-{"x"=>[{"y"=>[{"z"=>"1", "w"=>"2"}]}]}
+{"x"=>[{"y"=>[{"z"=>"1"}]}, {"y"=>[{"w"=>"2"}]}]}
```

**Comment by tenderlove** [comment]
@rthbound IIRC #1029 changes the way [an ambiguous case is parsed](https://github.com/rails/rails/issues/23997#issuecomment-224720796).  I *think* the plan is to revert the part that changes the ambiguous parsing behavior, but keep the rest.  @matthewd can you confirm?
