### ISSUE TITLE
Required Ruby >= 2.2.2?

### ISSUE THREAD

**Issue by lsegal** [rack/rack#1104]
Rack 2.x seems to force [Ruby >= 2.2.2 in the gemspec](https://github.com/rack/rack/blob/master/rack.gemspec#L29), but tests seem to pass under Ruby 2.1.x: https://travis-ci.org/lsegal/rack/jobs/148182677

Is there a reason for enforcing a minimum Ruby version requirement *for this library*? The related gemspec commits offer no explanation of why the requirement was added, and why it is so strict. This is extremely cumbersome when dealing with Ruby 2.1 apps that have large dependency graphs (eventually, one of them explicitly asks for Rack 2.x).

**Comment by deepj** [comment]
@lsegal it's due to Rails 5

**Comment by lsegal** [comment]
@deepj can you elaborate on this? Rack does not depend on Rails, and Rails itself already has its own minimum Ruby version specification.

**Comment by deepj** [comment]
@lsegal The best answer can give you @tenderlove. I might be wrong here. But I guess it's due to what I said.

**Comment by tenderlove** [comment]
> Is there a reason for enforcing a minimum Ruby version requirement for this library?

[2.1 has ended normal maintenance](https://www.ruby-lang.org/en/news/2016/02/24/support-plan-of-ruby-2-0-0-and-2-1/), so I don't really want to support it.  Since major releases of Rack are very few and far between, it gives us a good chance to trim dependencies.  Given the previous maintainers burn out, it seems better for project longevity.
