### ISSUE TITLE
parse_nested_query order dependency?

### ISSUE THREAD

**Issue by mockdeep** [rack/rack#1205]
It looks like this could be resolved on the Rails side by removing a `sort!`, but wanted to report this here in case it might be considered a bug in Rack. Basically, different ordering of hash params [can result in different results](https://github.com/rails/rails/issues/23997#issuecomment-328241673):

```ruby
pairs = [
  "routing_wizard[steps][][seq]=2",
  "routing_wizard[steps][][recipients_attributes][][name]=burger",
  "routing_wizard[steps][][recipients_attributes][][email]=burger1@gmail.com",
  "routing_wizard[steps][][type]=RecipientStep",
  "routing_wizard[steps][][seq]=3",
  "routing_wizard[steps][][recipients_attributes][][name]=fries",
  "routing_wizard[steps][][recipients_attributes][][email]=fries2@gmail.com",
  "routing_wizard[steps][][type]=RecipientStep",
]

Rack::Utils.parse_nested_query(pairs.join('&'))
# {
#   "routing_wizard"=>{
#     "steps"=> [
#       {"seq"=>"2", "recipients_attributes"=>[{"name"=>"burger", "email"=>"burger1@gmail.com"}], "type"=>"RecipientStep"},
#       {"seq"=>"3", "recipients_attributes"=>[{"name"=>"fries", "email"=>"fries2@gmail.com"}], "type"=>"RecipientStep"}
#     ]
#   }
# }

Rack::Utils.parse_nested_query(pairs.sort.join('&'))
# {
#   "routing_wizard"=>{
#     "steps"=>[
#       {"recipients_attributes"=>[{"email"=>"burger1@gmail.com"}, {"email"=>"fries2@gmail.com", "name"=>"burger"}, {"name"=>"fries"}], "seq"=>"2"},
#       {"seq"=>"3", "type"=>"RecipientStep"}, {"type"=>"RecipientStep"}
#     ]
#   }
# }
```

**Comment by jeremyevans** [comment]
I believe this is expected behavior.  When rack comes across the same key for a hash nested inside an array (`seq` in this case ), that's when it adds a new hash to the array as opposed to updating the current hash in the array.  Sorting the input breaks things in this case.  In general this isn't a problem as browsers will submit parameters in the order they appear on the form.

Personally, to avoid similar issues, I avoid arrays containing hashes when using rack's parameter parsing. For cases where I want an array of hashes, I format the parameters to use a hash of hashes, then sort by the key and map the values to get an array of hashes.
