### ISSUE TITLE
Broken range requests with Rack::File and WEBrick

### ISSUE THREAD

**Issue by pixeltrix** [rack/rack#1235]
The changes in e0ac329 and #753 mean that when `Rack::File` processes a range request the file object gets returned to WEBrick and the offset position is lost, resulting in the file being read from the beginning again.

**Comment by tenderlove** [comment]
@pixeltrix thanks for filing this.  This seems like kind of an ambiguity in `SPEC`.  `SPEC` says:

> If the Body responds to +to_path+, it must return a String
identifying the location of a file whose contents are identical
to that produced by calling +each+; this may be used by the
server as an alternative, possibly more efficient way to
transport the response.

I guess this means that range requests need to return a body that doesn't respond to `to_path`?  Kind of annoying since the webserver might be more efficient at serving up a static asset than our iterator object.  Regardless, I think the right approach is to return an object that doesn't respond to `to_path` on range requests (but only in this middleware).
