### ISSUE TITLE
Why does Rack::CommonLogger depends on #each being called for BodyProxy instance? #log method never called

### ISSUE THREAD

**Issue by macabl** [rack/rack#1345]
I has to subclass Rack::CommonLogger to perform logging in my rack app as follows:

```
module Rack
  class CommonLogger2 < CommonLogger
    def call(env)
      began_at = Utils.clock_time
      status, header, body = @app.call(env)
      header = Utils::HeaderHash.new(header)
      log(env, status, header, began_at)
      [status, header, body]
    end
  end
end
```

Why does Rack::CommonLogger depends on #each being called for BodyProxy instance?
https://github.com/rack/rack/blob/master/lib/rack/common_logger.rb#L37

Looks like the method #each for the BodyProxy instance was never called. Rack::CommonLogger is atop of my middleware chain.

**Comment by mig-hub** [comment]
@macabl, I am not entirely sure what the question is, but the body in rack must always respond to `:each`. This is in the [rack specs](https://github.com/rack/rack/blob/master/lib/rack/lint.rb#L705-L707). This is why if you look at the code of some middleware, when they only return a short string it is [wrapped in an array](https://github.com/rack/rack/blob/master/lib/rack/file.rb#L142-L154).

Since rack middlewares are chained, the fact that this particular one does not call `:each` does not matter. One further down the line will.

I hope it answers your question. Forgive me if I said something you already know.

**Comment by jeremyevans** [comment]
Rack::CommonLogger waits until `each` is called in order to correctly calculate the time spent processing the entire request, as that number is included in the log.  This is by design and not a bug.  The design has a tradeoff in that requests that don't process the entire body will not be logged, but the assumption is that shouldn't happen in most cases.
