### ISSUE TITLE
Rack mixes together headers with `-` and `_` in them

### ISSUE THREAD

**Issue by graywolf-at-work** [rack/rack#1374]
According to rack's spec, when two headers differs in only `-` and `_`, they are
merged together as if the name was exactly the same. You see that below:

```
+   $ curl -v -H 'foo-bar: Y' -H 'foo_bar: X'  localhost:9292
*   Trying ::1:9292...
* TCP_NODELAY set
* Connected to localhost (::1) port 9292 (#0)
> GET / HTTP/1.1
> Host: localhost:9292
> User-Agent: curl/7.65.1
> Accept: */*
> foo-bar: Y
> foo_bar: X
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Transfer-Encoding: chunked
<
* Connection #0 to host localhost left intact
```

```
run ->(env) do
  pp env
  [200, {}, ['']]
end
```

```
$ bundle exec rackup | grep HTTP_
 "HTTP_VERSION"=>"HTTP/1.1",
 "HTTP_HOST"=>"localhost:9292",
 "HTTP_USER_AGENT"=>"curl/7.65.1",
 "HTTP_ACCEPT"=>"*/*",
 "HTTP_FOO_BAR"=>"Y, X",
```

This can pose security threat (for example if only `-` variant is stripped on
a proxy but rack accepts both) and I do not believe this behavior is RFC
compliant (please correct me if I'm wrong).

I realize that rack's specification just defers to CGI RFC on this point (
https://tools.ietf.org/html/rfc3875#section-4.1.18 ), however that behaviour
is broken and should in my opinion not be used going forward, specifically I mean

```
[..] has all occurrences of "-" replaced with "_" [..]
```

Also it currently breaks other part of the RFC

```
If multiple header fields with the same field-name
are received then the server MUST rewrite them as a single value
having the same semantics.
```

since `foo-bar` and `foo_bar` are *not* the same http header field names. Also
it is in violation of

```
[..] can be rewritten in ways which do not change its semantics.
```

Because in our example `foo-bar` and `foo_bar` do not represent comma separated
values.

I see two possible fixes:

1. Parse `foo-bar` into `HTTP_FOO-BAR` and `foo_bar` into `HTTP_FOO_BAR`. That
   is much cleaner solution, however breaks all existing applications, which is
   probably bit of a downside. Would require major version bump.

2. Keep parsing `foo-bar` into `HTTP_FOO_BAR`, and parse `foo_bar` for example
   as `HTTP_FOO?BAR`. `?` is not a valid character in field name (
   https://tools.ietf.org/html/rfc7230#section-3.2 ), so it can work as a
   substitute.

Maybe ideal solution would be to apply fix 2. to current version and fix 1. to
next major version.

Also https://github.com/rack/rack/blob/master/test/spec_lint.rb#L217 is wrong,
should be

```
invalid_headers = 0.upto(32).map(&:chr) + %W<( ) , / : ; < = > ? @ [ \\ ] { } \x7F>
```

**Comment by ngetahun** [comment]
Is this issue up for grabs?

**Comment by speckins** [comment]
FWIW both Apache and nginx silently discard HTTP headers containing hyphens.

https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/#missing-disappearing-http-headers

**Comment by graywolf-at-work** [comment]
You can alway enable it (`underscores_in_headers on;`). Varnish and haproxy I believe do let them through in default configuration.

**Comment by jeremyevans** [comment]
I agree that the current behavior is undesirable. Fix 1 I also think is undesirable, as it breaks existing code and normal expectation.  Fix 2 I think is reasonable. As a possible fix 3, we may consider default behavior similar to Apache and Nginx (ignoring headers with underscores), with an option to allow underscores in headers (for the current behavior).

**Comment by ioquatix** [comment]
So, an example of this kind of issue, would be `Content_Length` vs `Content-Length` and at the protocol level having that cause framing issues, which then leads to all sorts of awesome security issues. This has happened in the past when some servers were case sensitive, e.g. `ContentLength` and `CoNtEnTlEnGtH`.

Fortunately, Rack is not designed as a proxy, and this is more a concern of middle boxes and servers, rather than Rack middleware.

Falcon normalises headers according to the RFC, and protocol level headers are passed using a rich `Protocol::HTTP::Request` object. So, it's not such a big concern for Falcon, but other servers probably have different behaviour.

Unfortunately, I can't see us solving this problem in Rack 2.x - even dropping headers with underscores might be breaking behaviour. What we **could** do is add a warning when this situation occurs. That would be the first step, IMHO. But that's going to be server specific, because Rack  doesn't provide the facilities for parsing headers, e.g.

https://docs.ruby-lang.org/en/2.5.0/WEBrick/HTTPRequest.html#method-i-meta_vars

```ruby
  self.each{|key, val|
    next if /^content-type$/i =~ key
    next if /^content-length$/i =~ key
    name = "HTTP_" + key
    name.gsub!(/-/o, "_")
    name.upcase!
    meta[name] = val
  }
```

So... I'm going to close this issue, not because there is anything fundamentally wrong about it, and it's definitely something that should be addressed., but just because it's out of scope for Rack as currently implemented.

That being said, I'd be keen to put warnings in Falcon.

**Comment by ioquatix** [comment]
cc @evanphx
