### ISSUE TITLE
etag not generated when Cache-Control: no-cache is present

### ISSUE THREAD

**Issue by henm** [rack/rack#1415]
In `Rack::ETag`, the etag is not generated when `Cache-Control: no-cache` is present (https://github.com/rack/rack/blob/master/lib/rack/etag.rb#L60).

According to the spec, the etag can be used for validation when `no-cache` is present, so does it make sense to not generate the etag in this case?

Documents and specifications:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#Directives
https://tools.ietf.org/html/rfc7234#section-5.2.1.4
https://tools.ietf.org/html/rfc7234#section-4.3

Thanks!

**Comment by ioquatix** [comment]
I think it's up to you to make the case that it does or does not. Then, make a PR to add this functionality, maybe behind an option, so that existing code using `Rack::ETag` doesn't suddenly change behaviour unexpectedly (or make the case that it should be the default).

Thanks in advance for your effort.

**Comment by jeremyevans** [comment]
As this isn't a bug (even if changing the behavior could be useful), I'm going to close this. Let's continue the discussion in #1416.
