### ISSUE TITLE
Reg CVE-2019-16782

### ISSUE THREAD

**Issue by prabhu** [rack/rack#1431]
Hello,

Thank you for fixing CVE-2019-16782 promptly. But I have a couple of concerns regarding this issue and the fix.

- I don't believe the vulnerability is that big. The amount of time needed to perform this attack is significant. This is not just a rack specific issue since it should be possible to replicate this on other web servers too
- Regarding the fix - it appears like the [patch](https://github.com/rack/rack/commit/7fecaee81f59926b6e1913511c90650e76673b38) has now created a backdoor (for a lack of better word). The session id comparison would succeed either with a private id or public id for the same session. Since the private id is a simple SHA256 of the public id it should be possible to retrieve this from localStorage and other storage where such a simple hashing gets used by developers. 

My recommendation would be to revert the fix till a proper analysis is done regarding the severity of the vulnerability.

Any thoughts?

**Comment by utkarsh2102** [comment]
The second point looks legit to me. However, of course, I haven't done any testing yet.
But in theory, yes, it looks like it.

**Comment by jeremyevans** [comment]
Regarding point 1, I agree that the vulnerability is not that great and does take substantial time to pull off.  However, that doesn't mean the issue should be ignored. We should attempt to prevent timing attacks to the extent feasible.

From a brief analysis, I'm not sure point 2 results in a more vulnerable situation than the previous behavior.  However, because the public id is still used, I believe a timing attack against it may still be possible.  However, because the private id is checked first, that probably makes such a timing attack substantially more difficult (maybe even infeasible).  Also, you would only be able to perform a timing attack against sessions created before the upgrade to a rack 1.6.12/2.0.8/2.1.0. @tenderlove this is the related line (https://github.com/rack/rack/commit/7fecaee81f59926b6e1913511c90650e76673b38#diff-f172203e9835038b18bfb8df650cea3aR81), do you agree with that analysis?

Note that the vulnerability only affects cases that use a non-constant time comparison of the session id (such as a database index).  The most common case is probably cookie sessions, which don't use the generated session id and I would think would be unaffected by this issue.  I don't think the session id is needed for cookie sessions at all, it just happens to be used because that is the behavior of the base class.

At this point, I don't think reverting the fix is a possibility.  Too many libraries have already started using the current API.  If you would like to recommend backwards-compatible changes to the current API, please submit a pull request for them.

**Comment by tenderlove** [comment]
@jeremyevans yes, I agree.  We need to remove the "automatic upgrading" in order to completely eliminate the timing attack.

**Comment by jeremyevans** [comment]
@tenderlove Do we want to remove the "automatic upgrading" completely in 2.2 or in 3.0?  Alternatively, allow turning it off or on via a flag, and default flag to on in 2.2 and off in 3.0?

**Comment by rafaelfranca** [comment]
@jeremyevans my plan was to allow turning off via a flag on 2.2 and remove it completely in 3.0.

**Comment by mjc-gh** [comment]
> Regarding the fix - it appears like the patch has now created a backdoor (for a lack of better word). The session id comparison would succeed either with a private id or public id for the same session. Since the private id is a simple SHA256 of the public id it should be possible to retrieve this from localStorage and other storage where such a simple hashing gets used by developers.

Are you suggesting that the timing attack is still possible because the computed private session ID is externally knowable?

Perhaps using an HMAC instead of just a hash function would prevent an attacker from being able to externally know the "lookup" value.
