### ISSUE TITLE
Considerations for response body implementing `#call`.

### ISSUE THREAD

**Issue by ioquatix** [rack/rack#1550]
I would like to update the SPEC in Rack 3 to allow the response body to respond to `#call` and remove all `rack.` response headers (e.g. `rack.hijack`).

The response should be the same as currently defined, e.g.

`[status, headers, body]` where body can respond to `#each` or, in Rack 3, `#call`.

The argument to the `#call` is a stream object, similar to `rack.hijack`.

The benefits are:

- Simpler SPEC.
- More efficient server implementation.

The challenges are:

- Existing middleware which responds with `[status, headers, self.dup]` where `self` implements `#call(env)`. I don't think this is a good pattern anyway, so we should find and eradicate it in the rack code base in preparation for this change in Rack 3, if we decided to go with this approach.

**Comment by tenderlove** [comment]
I've only thought about this for 2 minutes or so, but on the surface this seems like a good idea.

1. I don't know off the top of my head what all of the `rack.` headers are, so we need to look in to that.

2. How should middleware that want to do something depending on the response body be written?  For example a middleware that wants to set at `Content-Length` header, or a middleware that wants to rewrite links in a response body.

**Comment by jeremyevans** [comment]
It sounds like this is just for replacing response hijacking (after headers), and does not affect request hijacking (before status)?  Those currently have a nice symmetry, and would no longer have as nice a symmetry after this change.

We should only consider this change if `each` takes preference over `call`.  That is, if the body responds to `each`, `each` is called and hijacking is not attempted, regardless of whether the body responds to `call`.  This is necessary so that backwards compatibility is kept for users using bodies that support both `each` and `call`.

The SPEC itself does not get significantly simpler with this change, since the only change is where hijacking is looked for (headers or body).  As response hijacking is done after the headers are processed, you already know before sending the body whether to do hijacking currently.  With this change, you can't just call `body.each`, you have to check if the body responds to `each` first, and then call `call` if not.  The `respond_to?` check may be faster, but in the typical case there aren't that many headers, so I'm not sure how much more efficient this makes things.  Especially if we accept #1485 and can use `if headers['rack.hijack']` instead of `if !body.respond_to?(:each)`.

Regarding @tenderlove 's questions:

1. `rack.hijack` is the only response header mentioned in SPEC.  Other `rack.*` settings are request environment keys, not response header keys.

2. Currently, the response body is ignored when doing response hijacking.  So middleware that currently do something to body when using response hijacking do not make the desired change.  With current SPEC, if you want to modify the body, you need to iterate over the body using `each` to get the current body.  With this proposal, such middleware would raise a NoMethodError instead of having their body changes be ignored.  We could fix the cases in Rack itself, but this would break a ton of external middleware.

**Comment by ioquatix** [comment]
> I don't know off the top of my head what all of the rack. headers are, so we need to look in to that.

The main one I'm aware of are `rack.hijack`.

> How should middleware that want to do something depending on the response body be written? For example a middleware that wants to set at Content-Length header, or a middleware that wants to rewrite links in a response body.

This problem already affects `rack.hijack` and there is no easy solution.

The use case for returning a body that responds to `#call` is because you want to directly interact with the output stream.

That being said, if you did want to intercept this for whatever reason, you'd need to invoke `#call` with your own stream proxy and handle the buffering/streaming yourself.

> and does not affect request hijacking (before status)?

With HTTP/2, there is no "hijacking before status". So, this model is obsolete IMHO and therefore irrelevant.

The only model that works consistently with HTTP/1 and HTTP/2, which I've personally implemented in Falcon, is the one proposed here.

> This is necessary so that backwards compatibility is kept for users using bodies that support both each and call.

I've played around with both approaches in `falcon`. I can't remember what I preferred, but thinking about it now, `#call` should take priority over `#each` because `#each` might be implemented as a wrapper around `#call` for servers that don't support it. In any case, if we make it an official part of the SPEC in rack 3, we can define it whatever way makes sense, maybe as you suggested with `#each` taking priority, because it won't be needed as a fallback.

> The SPEC itself does not get significantly simpler with this change, since the only change is where hijacking is looked for (headers or body).

Hijack is a hack that ties very closely with the HTTP/1 model and is **very** tricky to implement with HTTP/2. However, falcon does it and provides access to the underlying HTTP/2 stream. There are some limitations... but I think they key point is, **`hijack` is a hack**.

In particular, I'd like to define the response headers as **only** valid HTTP headers. The `rack.` headers should all be removed. It's a mess to deal with them: https://github.com/socketry/falcon/blob/master/lib/falcon/adapters/response.rb#L36-L53

It definitely makes sense we should support something that better represents the streaming capabilities of HTTP/1 & HTTP/2, and `hijack` does provide a good basis for the design of a future interface.

> Especially if we accept #1485

This is kind of a hack though. The realty is, the headers being a hash is really not semantically correct. Additionally if we merge in the memoization of `HeaderHash`, we are taking a position where the headers could be an instance of that class. We could get more nuanced, like define the headers to have a case insensitive index method... all options to consider. But the current design is sufficient, **except** for `rack.hijack`.

> We could fix the cases in Rack itself, but this would break a ton of external middleware.

It's easy enough to provide a fallback for `#each` -> `#call` though. That being said, trying to call `#each` on a websocket connection won't result in desirable results :p

**Comment by ioquatix** [comment]
Reference to https://github.com/rack/rack/issues/1148 which also discusses dropping the requirement for `#rewind` on request body, which should probably be considered in a separate issue.

**Comment by jeremyevans** [comment]
> The main one I'm aware of are `rack.hijack`.

This is the only `rack.` response header mentioned in SPEC.  Treating other `rack.` entries in the response headers specially (including case insensitivity) is going beyond what SPEC requires.  Unicorn only handles "rack.hijack" and is case sensitive. 

> With HTTP/2, there is no "hijacking before status". So, this model is obsolete IMHO and therefore irrelevant.

I disagree with this. HTTP/1 is still the more important protocol, IMO.  Plenty of existing software using request hijacking, such as MessageBus.  However, since it may not be related to this proposal to support `body#call`, we can treat it as irrelevant to this issue.

> Hijack is a hack that ties very closely with the HTTP/1 model and is **very** tricky to implement with HTTP/2. However, falcon does it and provides access to the underlying HTTP/2 stream. There are some limitations... but I think they key point is, **`hijack` is a hack**.

I thought this proposal was for `body#call` with the same semantics as the current `rack.hijack` response header.  I agree that hijack is a hack, and I thought that everyone agreed with that.  This proposal just changes where the hijack object is, it doesn't change the semantics, so using `body#call` is just as much of a hack as current hijacking.  At least with the current approach, the hack feels hacky instead of natural.

> The realty is, the headers being a hash is really not semantically correct. Additionally if we merge in the memoization of `HeaderHash`, we are taking a position where the headers could be an instance of that class.

#1485 is compatible with `HeaderHash` memoization, as `HeaderHash` subclasses `Hash`.  Memoization is not actually relevant, since memoization or not, all middleware using `HeaderHash` are generally returning the `HeaderHash` instance as the 2nd element of the response.

> We could get more nuanced, like define the headers to have a case insensitive index method... all options to consider.

That would break the use of a standard Ruby Hash, so I'm very against that.

> But the current design is sufficient, **except** for `rack.hijack`.

Again, `rack.hijack` response header and `body#call` are basically the same except for the location of the hijack object.  `body#call` is hijacking, just with a nicer interface.

**Comment by ioquatix** [comment]
Just realised I already outliend changes to the SPEC to implement this https://github.com/rack/rack/pull/1360

Maybe need to revisit it but at least it is an idea of what I was thinking 12 months ago.

**Comment by boazsegev** [comment]
@ioquatix ,

Thank you for your suggestion and for opening this discussion.

If I understand the proposal clearly, this will require the server to test if the `body` in the response answers the `#call` method (i.e., using `respond_to?`):

https://github.com/rack/rack/blob/33faf3b07d7eb3df7f1cf61b995238e1e323b853/SPEC#L194-L199

IMHO, making `body#call` optional will be sub-optimal for performance. This is since the `respond_to?` method requires Ruby to traverse the method and inheritance tree (possibly twice, once for the test and again for the execution)... this may be equivalent to a number of hash table lookups (instead of a single lookup).

Alternative approaches, such as setting a value in the `env` object (instead of a response header), such as proposed by #1272, will keep the performance the same or may even perform better (by setting the key to a `nil` value during the `env` initialization, lookup times are faster).

Additionally, some middleware might wrap the `body` object in order to perform cleanup operations within a call to `#close` (such as returning a database connection to the database pool or other similar actions). This would effectively negate the `#call` approach unless these implementations were updated to become "`#call` aware".

I agree that the `rack.hijack` header doesn't sit well with the functionality of a `response` object. A design change in this regard would be appreciated.

It seems to me that the `response` should contain only data that communicates with the "client" (not the server). IMHO, the same is true for `body#call`. Updating the environment makes more sense when communicating with the server than updating outgoing response.

**Comment by jeremyevans** [comment]
Handling this via a key in the `env` just moves it from one hash table to another.  It may make more semantic sense, but I'm not sure that alone is worth the backwards compatibility breakage.  I don't have any major issue with such a change, though.  We'd have to find a new name, since `rack.hijack` is already used for request hijacking.  `rack.response_hijack` maybe?

**Comment by ioquatix** [comment]
In practice, I could not see a huge difference, and don't think it's going to make much difference, all things considered:

```
#!/usr/bin/env ruby
# frozen_string_literal: true

require 'benchmark/ips'

GC.disable

class FakeBody
	def each
		yield "Fake Body"
	end
end

object = FakeBody.new

class Stream
	def write(chunk)
	end
end

stream = Stream.new

proc = Proc.new do |stream|
	stream.write "Fake Body"
end

hash = Hash.new
10.times do |i|
	hash['fake-header-i'] = i
end

hijack_hash = hash.dup
hijack_hash['rack.hijack'] = proc

Benchmark.ips do |benchmark|
	benchmark.time = 1
	benchmark.warmup = 1
	
	benchmark.report("object") do |count|
		while count > 0
			if object.respond_to?(:call)
				object.call(stream)
			else
				object.each{|x| stream.write(x)}
			end
			
			count -= 1
		end
	end
	
	benchmark.report("proc") do |count|
		while count > 0
			if proc.respond_to?(:call)
				proc.call(stream)
			else
				object.each{|x| stream.write(x)}
			end
			
			count -= 1
		end
	end
	
	benchmark.report("hash") do |count|
		while count > 0
			if hijack = hash['rack.hijack']
				hijack.call(stream)
			else
				object.each{|x| stream.write(x)}
			end
			
			count -= 1
		end
	end
	
	benchmark.report("hijack-hash") do |count|
		while count > 0
			if hijack = hijack_hash['rack.hijack']
				hijack.call(stream)
			else
				object.each{|x| stream.write(x)}
			end
			
			count -= 1
		end
	end
	
	benchmark.compare!
end
```

```
Warming up --------------------------------------
              object   357.879k i/100ms
                proc   390.421k i/100ms
                hash   368.792k i/100ms
         hijack-hash   395.439k i/100ms
Calculating -------------------------------------
              object      9.533M (± 0.5%) i/s -      9.663M in   1.013670s
                proc     11.695M (± 0.6%) i/s -     11.713M in   1.001578s
                hash     10.692M (± 0.4%) i/s -     10.695M in   1.000321s
         hijack-hash     12.413M (± 1.4%) i/s -     12.654M in   1.019599s

Comparison:
         hijack-hash: 12413255.0 i/s
                proc: 11694644.6 i/s - 1.06x  slower
                hash: 10691677.1 i/s - 1.16x  slower
              object:  9532620.2 i/s - 1.30x  slower
```

Thoughts?

**Comment by ioquatix** [comment]
Modifying `env` is not reliable in my experience, middleware might do `env.dup` or provide an entirely different `env`, when you modify it the changes never make it back out to the server. But good idea!

**Comment by boazsegev** [comment]
> Modifying `env` is not reliable in my experience, middleware might do `env.dup` or provide an entirely different `env`

Doesn't that break Hijacking (the non-delayed HTTP/1 variety)?

I mean, how does the server set the `rack.hijack_io` value in the `env` if it lost access to the (application's) `env` object...?

IMHO, such an approach should be considered broken to begin with and shouldn't be considered as a valid use-case.

Perhaps we should point it out in the SPECs (that the original `env` object should be forwarded to the application and middleware MUST NOT duplicate the `env` object)... though I thought it was clearly inferred 🤔

Even if we don't clarify this in the specification, since calling `env.dup` will break the current hijacking specification, I think we can ignore this edge case.

> In practice... (benchmark)

You're probably right. Even though your benchmark might be biased, the difference is not meaningful when using simple objects (the `body` object doesn't have a complex inheritance tree or a lot of methods).

I don't know if the same is true for complex objects (what if `call` is inherited using a mixin?).

As a side note: whenever `each` is used, an implicit `Proc` object is created, making the `each` code-path always slower.

For example, add the following sanity tests to the benchmark, they will show a slight difference in speed (and a difference in memory usage):

```ruby
  benchmark.report("sanity each") do |count|
    while count > 0
      count -= 1
      object.each{|x| stream.write(x)}
    end
  end
  benchmark.report("sanity call") do |count|
    while count > 0
      count -= 1
      proc.call(stream)
    end
  end
```

I ran a modified version on my machine (fixing the `hash['fake-header-i'] = i` to `hash['fake-header-#{i}'] = i.to_s`.

It's probably meaningless to see that `proc` enjoys a slight speedup by defining the `call` method (vs. a miss when the method is missing) - same is true for the `hijack-hash` enjoying a "hit" vs. a miss.

**Comment by ioquatix** [comment]
> Doesn't that break Hijacking (the non-delayed HTTP/1 variety)?

The `rack.hijack` spec is not completely specified. All servers return the I/O object, so even if you can't get it from `env`, you can get it as the result of calling the hijack proc:

https://github.com/socketry/falcon/blob/b8e9ca5aeaf748bec550a54a8bcdeb7f7c3d3fe7/lib/falcon/adapters/rack.rb#L169-L181

All servers I tested do this.

> IMHO, such an approach should be considered broken to begin with and shouldn't be considered as a valid use-case.

Well, yes, it's kind of a mess which is what we want to try and fix. Maybe in the 2.x branch, we can at least specify this behaviour clearly since servers already conform to it.

> Regarding benchmarks

Benchmarks are always subjective so just take it with a grain of salt. You were right in that hash lookup is a bit faster. However, I think the interface ergonomics are more important at this point. So, great to have this detailed discussion, but let's also consider what kind of interface we want to give to the user and implement on the server.

**Comment by boazsegev** [comment]
>  I think the interface ergonomics are more important at this point.

Agreed. Your benchmark shows that the performance consideration is somewhat meaningless.

We should focus on ease of use for the design. I also think it would be nice to if the design made intuitive sense. 

For me, and it is a personal thing, the response is the data I'm sending the client, while the `env` represents the connection's state and behavior.

When I call `env['rack.hijack'].call`, I am "speaking" to the state of the connection. When I authenticate a client and save the authentication in the `env` variable, I tested and updated the state of the connection... it's like a connection specific global state-machine.

This is why I believe using the `env` is "cleaner" and more intuitive. It's also more extendable than using `call`. There's only one `call` method but an endless number of `env` key-value possibilities.

> middleware might do `env.dup` or provide an entirely different `env`...

Please note that the same is true for the `body` object.

Middleware might wrap the body object in order to perform cleanup operations within a call to `#close` (as I mentioned above).

This approach is sometimes used for performance analysis as well as database connection "checkout" approaches.

This would break the `#call` method unless all `body` wrapping middleware is updated.

> All servers return the I/O object...

True, [iodine does so as well](https://github.com/boazsegev/iodine/blob/9e32fa7e430e7fe4767b7fa8ea4e9c990e7dcfcd/ext/iodine/iodine_rack_io.c#L185-L207), even though it's only a recommendation.

My observation is that - if we need to ask developers to update their middleware - it would probably be more polite to ask developers to fix problematic middleware rather than revisit middleware that works "as expected".

Setting the `rack.hijack_io` value allows other code paths to test for hijacking - something that can't be performed when using `env.dup`. This makes `env.dup` implementations inherently problematic.

For example, the specifications allows developers to assume that the IO object is stored in the `env` hash (so they don't have to save it to another variable), and `env.dup` breaks that expectation... this could result in failed `write` operations, etc'.

All in all, I believe that the `env.dup` could be considered a bug, which isn't something that could be said about the `body` wrapping approach.

> great to have this detailed discussion, but let's also consider what kind of interface we want to give to the user and implement on the server

I agree, it's a pleasure to be able to voice my opinion and debate these questions. In the end, we all love Ruby and Rack and we do our best to make it better.

I believe we're discussing "nice" vs. "sweet" - all three approaches work (existing, `body` and `env`). I'm partial towards the `env` approach, but it's my personal opinion, my vote, no more.

**Comment by ioquatix** [comment]
The problem that underpins all of this is that `rack.hijack` in whatever form it takes, fundamentally means that a layered approach to the output body becomes impossible.

That being said, you should only really do this when you actually intend to take full control of the output stream.

So, to me, conceptually, the hijack operation completely bypasses the rack stack and changes all the assumptions for middleware which is trying to manipulate the response body.

So, whatever way we look at it, either we are a normal response with a body that response to `#each`, or we are something else.

The `#each` interface is super intuitive and composable.

A body that responds to call, which accepts a stream with a well defined interface, is also somewhat composable, because you can wrap the response body in something which wraps the buffer, e.g.

```
class Wrapper
  def initialize(body)
    @body = body
  end
  
  def call(stream)
    @body.call(UpperCaseStreamWrapper.new(stream))
  end
end

def call(env)
  status, headers, body = @app.call(env)

  if body.respond_to?(:call)
    return status, headers, Wrapper.new(body)
  end
end
```

**Comment by boazsegev** [comment]
@ioquatix 

I agree with much of your assessment of `hijack`.

However, your Wrapper approach could as easily be performed with an `env` approach rather than a `body#call` approach.

Besides being vulnerable to `Wrapper` classes that aren't `call` aware (vs. being vulnerable to `env.dup`), I don't see much of a difference between the two.

In fact, you can do the same wrapping magic with the current header design:

```ruby
status, headers, body = @app.call(env)
headers['rack.hijack'] = Wrapper.new(headers['rack.hijack']) if headers['rack.hijack']
return status, headers, body
```

**Comment by ioquatix** [comment]
The only reason to make `#call` a first class primitive in Rack 3.0 is to solidify this model and ensure middleware DO handle it correctly. A response header like `rack.hijack` is simply too easy to ignore. So the point of this is, if we were to itemise changes for Rack 3.0, even though users could do what you propose, I don't think anyone does in practice.

So the result would be:

- Removing full hijack.
- Replace partial hijack with `body.call(stream)`.

There is one other point to consider.

There has been some discussion around the surface area of Rack.

Right now, it's actually pretty big.

Higher level frameworks like Rails may not depend on middleware, and middleware DO add overhead because of their chained implementation.

A lower level implementation might make more sense.

e.g.

```
# Hypothetical Rack 3.0 config.ru

def call(request, response)
  request.headers
  request.path
  response.status = 300
  response.headers = {...}
  response.write(chunk)
  response.push(promise)
  response.close
end
```

So, we completely remove the middleware stack, CGI variables, everything, and simply figure out a new, low level interface for servers.

That doesn't mean someone can't build the middleware stack on top of that. So, `Rack::Middleware` could still exist. We just provide a better interface for servers to implement - agnostic, stream based, etc.

**Comment by ioquatix** [comment]
In the above case, the Rack "SPEC" would become literally the call operation, and the request and response objects (which could be rich but opaque).

**Comment by ioquatix** [comment]
If we did decide to go this route, I'd like to try and find alignment with these implementations:

https://github.com/socketry/protocol-http/blob/master/lib/protocol/http/request.rb

https://github.com/socketry/protocol-http/blob/master/lib/protocol/http/response.rb

@tenderlove Once we get Rack 2.2 out the door (should be soon I hope), we could really start having a good hack and slash branch to see if this kind of model works and makes sense. Ideally we get at least 2-3 servers on board with prototype implementations.

ping @evanphx

**Comment by ioquatix** [comment]
I'll have a hack at this and I propose `rack.rb` to be a new convention with a single method `def call(request, response)` everything else tbd.

**Comment by jeremyevans** [comment]
I am very much against the `call(request, response)` approach to SPEC, unless we agree to provide a backwards-compatible implementation that works with the current SPEC and supports existing applications, frameworks, middleware, and servers. I don't think there is even a small possibility that the advantages of a `call(request, response)` approach outweigh the loss of backwards compatibility with all existing Rack applications, frameworks, middleware, and servers.

If you want to create a completely different and incompatible interface, you should create a new project, IMO.  If the approach is clearly better, certainly applications, frameworks, middleware, and servers may switch to it. However, Rack 3.x should remain mostly backwards compatible for existing clients, just as Rack 2.x was pretty much compatible with Rack 1.x.

**Comment by ioquatix** [comment]
I think the idea would be that we define a low level interface for servers, and still present the `Rack::Builder` on top of that. So Rack 3.0 would be compatible with `config.ru` style apps. But servers would agree to and implement a lower level interface which could also be exposed and would minimise the contention regarding how we deal with these issues. For example, `rack.hijack` could be completely deprecated/removed, if we provide a different (but consistent) interface at a lower level which exposes the interfaces required for streaming.

**Comment by ioquatix** [comment]
While Rails is probably in a hard space w.r.t. backwards compatibility, I've definitely heard rumblings that they'd rather not deal with rack middleware and that the overhead of middleware is not worth the flexibility that it brings, since they do their own internal request processing.

**Comment by jeremyevans** [comment]
I'll withhold further judgement until seeing an implementation, but I feel in the strongest possible terms that breaking backwards compatibility with existing applications, frameworks, middleware, and servers is not something we should do.

**Comment by ioquatix** [comment]
> breaking backwards compatibility with existing applications, frameworks, middleware, and servers is not something we should do.

Completely agree.

**Comment by ioquatix** [comment]
I'm going to open a new issue with a concrete proposal based on the discussion in this issue.
