### ISSUE TITLE
Sendfile documentation

### ISSUE THREAD

**Issue by ioquatix** [rack/rack#1556]
@jeremyevans @tenderlove & anyone else can you please check this?

Here was my original commit to fix the documentation for `Rack::Sendfile`.

https://github.com/rack/rack/commit/b790899d574833f8a9a9e62f6b352c22e32e0a80#diff-b6f6fdd6628c58cec9c7906b4c5275f3

It was based on my understanding as follows:

```
proxy_set_header   X-Accel-Mapping     /var/www/=/files/;
```

This is mapping a file like `/files/myfile.txt` (path part of `http://myserver/files/myfile.txt`) to `/var/www/myfile.txt` so that Nginx can serve it using sendfile.

Taking the code from the bottom of the `Rack::Sendfile` implementation, along with the original documentation, we get this:

```
HTTP_X_ACCEL_MAPPING = "/var/www/=/files/"

def map(path)
	HTTP_X_ACCEL_MAPPING.split(',').map(&:strip).each do |m|
		internal, external = m.split('=', 2).map(&:strip)
		new_path = path.sub(/^#{internal}/i, external)
		return new_path unless path == new_path
	end

	return path
end

puts map("/files/myfile.txt")
# => "/files/myfile.txt"
```

It seems wrong to me. So it should be:

```
HTTP_X_ACCEL_MAPPING = "/files/=/var/www/"
```

I updated the documentation, but then it was reverted by https://github.com/rack/rack/commits?author=nleguen with no explanation.

One of us is wrong. I don't mind if it's me, but can someone please check it so we can fix this once and for all? Because I don't just want to revert it if I'm wrong, and I can't see how I'm wrong, so either I'm blind or ignorant (or both).

**Comment by matthewd** [comment]
You're wrong. 😄

> This is mapping a file like /files/myfile.txt (path part of http://myserver/files/myfile.txt) to /var/www/myfile.txt so that Nginx can serve it using sendfile.

No. (But yes, but no...)

`Rack::SendFile` is starting with the on-disk path `/var/www/myfile.txt`, and trying to map it back to a virtual path that nginx will be able to re-resolve into that same physical path:

```
puts map("/var/www/myfile.txt")
# => "/files/myfile.txt"

# "If we tell nginx to serve the virtual resource /files/myfile.txt, 
#  it will spit out the contents of actual-file /var/www/myfile.txt"
```

Our objective isn't to _do_ the mapping, but rather to use foreknowledge _of_ the mapping that nginx will apply, to reverse-engineer a URI that it will ultimately re-map back into our target filesystem path.

> it was reverted [..] with no explanation

I mean... #209 seems to contain no more or less explanation than #198 (itself a revert of even-more-taciturn 4765f173dbf28cfff771013e1064650d042f0b72), so I'd rather assume everyone was doing their best at the time. There was a bit more discussion in #200.

---

Now, all that being said, I do personally find the `/virtual/=/actual/file/` arrangement to feel more intuitive (if only because virtual is generally going to be much shorter)... but that's not what the current implementation expects, as far as I can see. (The implementation could probably benefit from using `filesystem_path` and `virtual` instead of `internal` and `external` -- the latter don't do a particularly great job of capturing the relationship between any of these components, IMHO.)

**Comment by ioquatix** [comment]
Okay, great, I'm glad there was some discussion about it, I couldn't find it.
