### ISSUE TITLE
TypeError: no implicit conversion of nil into String with 2.2.1

### ISSUE THREAD

**Issue by charleskorn** [rack/rack#1583]
I'm receiving the following error when starting my application after upgrading Rack from 2.1.2 to 2.2.1:

```
TypeError: no implicit conversion of nil into String
  /app/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/rack/adapter/loader.rb:25:in `join'
  /app/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/rack/adapter/loader.rb:25:in `block in guess'
  /app/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/rack/adapter/loader.rb:24:in `each'
  /app/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/rack/adapter/loader.rb:24:in `guess'
  /app/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/thin/controllers/controller.rb:168:in `load_adapter'
  /app/vendor/bundle/ruby/2.7.0/gems/thin-1.7.2/lib/thin/controllers/controller.rb:74:in `start'
  /app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.1/lib/rack/handler/thin.rb:27:in `run'
  /app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.1/lib/rack/server.rb:327:in `start'
  /app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.1/lib/rack/server.rb:168:in `start'
  /app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.1/bin/rackup:5:in `<top (required)>'
  /app/vendor/bundle/ruby/2.7.0/bin/rackup:23:in `load'
  /app/vendor/bundle/ruby/2.7.0/bin/rackup:23:in `<top (required)>'
```

I'm running `rackup` like this: `bundle exec rackup -p 4567 -o 0.0.0.0`

My `config.ru` looks like this:

```ruby
# frozen_string_literal: true

require 'rubygems'
require 'bundler'

Bundler.setup
$LOAD_PATH << './lib'

require 'international_transfers_service'
run InternationalTransfersServiceApp
```

The full repo is available in https://github.com/batect/batect-sample-ruby/pull/145.

**Comment by ioquatix** [comment]
On this line:

https://github.com/macournoyer/thin/blob/f83ab677f008afcfabcdfa8930225f6cea88f461/lib/rack/adapter/loader.rb

`dir` is nil. `dir` comes from this line:

https://github.com/macournoyer/thin/blob/f83ab677f008afcfabcdfa8930225f6cea88f461/lib/thin/controllers/controller.rb#L168

`@options` is

```
{:environment=>"development",
 :pid=>nil,
 :Port=>9292,
 :Host=>"localhost",
 :AccessLog=>[],
 :config=>"/Users/samuel/Documents/rack/app/config.ru",
 :address=>"localhost",
 :port=>9292}
```

So it doesn't include `chdir`.

I checked `2-1-stable` and I couldn't find any reference to a chdir option.

Looking at thin, I see:

https://github.com/macournoyer/thin/blob/f83ab677f008afcfabcdfa8930225f6cea88f461/lib/thin/runner.rb#L36-L49

which is provided to the controller here:

https://github.com/macournoyer/thin/blob/f83ab677f008afcfabcdfa8930225f6cea88f461/lib/thin/runner.rb#L198

But when using `rackup` it goes via the code here:

https://github.com/rack/rack/blob/master/lib/rack/handler/thin.rb#L27

I don't think this is providing `chdir`. Looking at the history of that file, I can't see how it ever worked... since I can't see that we ever provided that option.

**Comment by ioquatix** [comment]
Okay, I think I found the problem.

https://github.com/rack/rack/commit/371bd586d188d358875676bc37348db9a0bf7a07#diff-e04002084f4028e511d1ec329d37c391

In this commit, we changed from using `Thin::Server` to `Thin::Controllers::Controller`. This seems to have broken thin. Because `Thin::Controllers::Controller` requires the `:chdir` option.

@jeremyevans I guess we need to add a default `:chdir` option and additionally, if we are going to continue to support thin, we should add some tests for it.

Ideally, we'd probably test all rackup servers.

**Comment by ioquatix** [comment]
You have two options right now.

- Stay on rack 2.1.2
- Use a different server.

**Comment by jeremyevans** [comment]
Sorry about that.  I have no knowledge of Thin, and the issue report and recommended fix looked reasonable to me.  In general, required options are a pretty bad.

I will revert the commit to restore compatibility.

**Comment by poloka** [comment]
@jeremyevans is there an ETA to when v2.2.2 will be released?

**Comment by jeremyevans** [comment]
@poloka I believe @ioquatix is planning a release soon, probably today or tomorrow.

**Comment by ioquatix** [comment]
Yes, I will be doing it now.
