### ISSUE TITLE
The focus of Rack.

### ISSUE THREAD

**Issue by ioquatix** [rack/rack#1593]
Rack was designed around providing a bridge between web applications and web servers. The interface it currently presents is high level, loosely based on the CGI model.

This model presents a number of challenges when considering the direction of the modern web, including things like WebSockets, streaming requests & responses, etc. Things like `rack.hijack` are shoe-horned into the existing model but are not a good fit. Proposed fixes to these issues (e.g. https://github.com/rack/rack/issues/1550) don't really solve the core problem and potentially introduce compatibility issues.

I think we all agree that the Rack middleware structure is great and has been a boon to the proliferation of web application frameworks. However, it presents a fairly different interface from what underlying web-servers are actually doing. Therefore, `rack` is no longer a minimal bridge, but almost an application framework in it's own right. `rack` as a gem now encompasses many things:

- `rackup` command for running web applications. But it's only really sufficient for development purposes.
- `Rack::Session` handling which is not a concern of web server <-> web application, but is more an application layer concern.
- Lots of middleware, some of which is completely irrelevant, which must be versioned and maintained.

Binding all these pieces together makes it complicated to manage the code and releases. Recent security fixes in session management must be back ported. If the session code was a separate gem e.g. `rack-session` it could be versioned independently and the need for updating the core of `rack` would be less important. Additionally, because of the implementation, we are bringing in additional dependencies (e.g. memcached) which have little to do with the core functionality of `rack`.

For a long time, handlers for servers have been built into rack, both showing a tacit preference (it took 2-3 years for Falcon to get accepted into the server list) and providing interfaces to servers which don't provide enough flexibility (e.g. the recent `thin` integration issues).

The scope of `rack` includes lots of pieces which are in excess of it's original vision, which was a bridge between web servers and web applications. `rack` has extended into the space of web applications and it's both a maintenance burden and not particularly useful for the vast majority of systems.

As such, I think we should consider returning our focus to the bridge between web server and web application.

**Comment by jeremyevans** [comment]
> Rack was designed around providing a bridge between web applications and web servers. The interface it currently presents is high level, loosely based on the CGI model.

Agreed, and I think this is for the best.

> This model presents a number of challenges when considering the direction of the modern web, including things like WebSockets, streaming requests & responses, etc. Things like `rack.hijack` are shoe-horned into the existing model but are not a good fit. Proposed fixes to these issues (e.g. #1550) don't really solve the core problem and potentially introduce compatibility issues.

Agreed.  `rack.hijack` is a hack, a backdoor, something that requires care to use correctly.

> I think we all agree that the Rack middleware structure is great and has been a boon to the proliferation of web application frameworks. However, it presents a fairly different interface from what underlying web-servers are actually doing.

Agreed, and I don't think that is necessarily a bad thing.  Rack (other than hijack) presents a very simple API: `env` input and `status, headers, body` output.  In my opinion, this is rack's best feature, and we should not change it.

> Therefore, `rack` is no longer a minimal bridge, but almost an application framework in it's own right.

I would say that the rack SPEC is a minimal bridge, minimal enough that many servers don't even require rack, and web frameworks and middleware don't need to (though many do).

I'm not sure I would classify rack as "almost an application framework", though it is true that rack ships with basically pieces of framework-like code.

>`rack` as a gem now encompasses many things:
> 
> * `rackup` command for running web applications. But it's only really sufficient for development purposes.

While I don't personally do so, `rackup` can be used with real servers (e.g. puma) in production mode, and even is designed to handle production concerns such as daemonization.

> * `Rack::Session` handling which is not a concern of web server <-> web application, but is more an application layer concern.

Correct.  However, session handling is tricky to get both correct and secure.  Not having it in rack would result in many frameworks implementing it incorrectly.  Most rack frameworks use rack's session support.

> * Lots of middleware, some of which is completely irrelevant, which must be versioned and maintained.

Agreed.

> Binding all these pieces together makes it complicated to manage the code and releases. Recent security fixes in session management must be back ported. If the session code was a separate gem e.g. `rack-session` it could be versioned independently and the need for updating the core of `rack` would be less important. Additionally, because of the implementation, we are bringing in additional dependencies (e.g. memcached) which have little to do with the core functionality of `rack`.

I think the memcache dependency is now gone.  We can probably remove rack/session/memcache, since I think it has been deprecated since at least rack 2.1.

> For a long time, handlers for servers have been built into rack, both showing a tacit preference (it took 2-3 years for Falcon to get accepted into the server list) and providing interfaces to servers which don't provide enough flexibility (e.g. the recent `thin` integration issues).

Agreed.

> The scope of `rack` includes lots of pieces which are in excess of it's original vision, which was a bridge between web servers and web applications. `rack` has extended into the space of web applications and it's both a maintenance burden and not particularly useful for the vast majority of systems.

I somewhat agree with this.  However, rack does have significant parts that are both useful and widely used (e.g. Request).

> As such, I think we should consider returning our focus to the bridge between web server and web application.

I agreed with this, but I also think we should keep backwards compatibility to the extent feasible.  We should only drop code that is a maintenance burden.  We should be conservative in terms of changing SPEC, and try to limit changes to it so that existing servers, frameworks, middleware, and applications continue to work, or work with as minimal changes as possible.

**Comment by ioquatix** [comment]
I want to revisit some of these ideas with an emphasis on making practical changes for Rack v3.0

One of these might be extracting some of the session handling code into a separate gem along with deleting/moving middleware.

**Comment by ioquatix** [comment]
We have cut issues for all the specific points mentioned in this issue.
