### ISSUE TITLE
Move `Rack::Session` to new `rack-session` gem.

### ISSUE THREAD

**Issue by ioquatix** [rack/rack#1596]
`Rack::Session` is an important piece of rack. However, it has quite a different life from `rack`, in the sense that:

- It might be useful to version it independently of Rack, i.e. to fix security issues without requiring users to update/change `rack` versions and/or backporting.
- There are no strict dependencies between `rack` and `rack-session`. They are largely independent of each other.
- Users who don't need session management can simply avoid it completely.

I propose to move the code of `Rack::Session` into it's own gem.

**Comment by rafaelfranca** [comment]
👍

**Comment by fatkodima** [comment]
@ioquatix I can help with this, if you are interested in.

**Comment by maboelnour** [comment]
Is this still needed? If yes, I can investigate it.

**Comment by jeremyevans** [comment]
I was originally against this, but after a lot of thought, I am now in favor.  Originally, I was thinking Rack 3 would be more compatible with Rack 2, so the backwards compatibility breakage was not worth it.  However, considering the other backwards compatibility breakage in Rack 3 (lower case headers), moving the session support to a separate gem seems small in comparison.

I think we should do the work to merge #1177 before extraction, so that it doesn't need to be re-added as a pull request to the new rack-session repository.

**Comment by jeremyevans** [comment]
This was committed in 1085a3e97162a8b1675ae896f7c2158e6f00d1fc.
