### ISSUE TITLE
Rack 3.0 minimum Ruby version

### ISSUE THREAD

**Issue by ioquatix** [rack/rack#1601]
By the time we release Rack 3.0, I believe Ruby 2.4 will be EOL.

There are a few functions we would prefer to use, including `#tranform_keys`.

Do we want to support EOL Rubies? What would be a reasonable policy?

**Comment by matthewd** [comment]
It's certainly not the deciding factor, but FWIW, the Rails 6.x series requires Ruby 2.5. 

If anything, that's mostly relevant in the other direction: we're ~going to~ _expecting_ to support 2.5 for a new release in 2021, so we'd prefer new Rack releases to also maintain support for that version until then (because otherwise we won't be able to use them).

That desire aside, I think it's generally reasonable to drop support for EOLed Ruby versions during major version bumps, even for deep infrastructure level projects like Rack. The disruption of the library upgrade will dwarf any disruption from a corresponding Ruby upgrade; it's not reasonable for people to expect us to help them be able to do the hard thing while skipping the easy one.

**Comment by simi** [comment]
Just to remind, there are some stats available at http://ecosystem.rubytogether.org/ and `2.3` seems still widely used for some reason.

**Comment by natematykiewicz** [comment]
As of today, Ruby 2.4 support has ended. https://twitter.com/rubylangorg/status/1249125876492615681?s=21

**Comment by jeremyevans** [comment]
IMO, central infrastructure such as rack should only drop old ruby versions when doing so becomes a maintenance burden.  There is some Ruby <2.4 compatibility code we could remove (dropping 2.3 support), but I don't see any reason to drop Ruby 2.4 support just because it is no longer supported by ruby-core.

**Comment by natematykiewicz** [comment]
I just mentioned it, since the originally post mentioned Ruby 2.4.

**Comment by ioquatix** [comment]
We have dropped support for Ruby 2.3 and I believe we will continue to be pragmatic about it.
