### ISSUE TITLE
Breaking changes in 2.1.0 and 2.2.0

### ISSUE THREAD

**Issue by BobbyMcWho** [rack/rack#1612]
Hello, I was going about releasing a new version of omniauth to unpin the hashie version requirement, and we're getting a [failing CI build](https://travis-ci.org/omniauth/omniauth/builds/655540843) using rack 2.2.0. 

Going to rack 2.1.0 locally introduces a test failure [here](https://github.com/omniauth/omniauth/blob/master/spec/omniauth/strategy_spec.rb#L245). 
```
  2) OmniAuth::Strategy#redirect uses javascript if :iframe is true
     Failure/Error: end
     
     NoMethodError:
       undefined method `body' for #<Array:0x00007fe8cfa58178>
     # ./spec/omniauth/strategy_spec.rb:247:in `block (3 levels) in <top (required)>'
```

Going to 2.2.0 introduces an additional failure [here](https://github.com/omniauth/omniauth/blob/master/spec/omniauth/strategy_spec.rb#L655-L656).

```
1) OmniAuth::Strategy#call test mode maintains host and port
     Failure/Error:
     
       expected: "http://example.org:3000/auth/test/callback"
            got: "http://example.org/auth/test/callback"
     
       (compared using ==)
     # ./spec/omniauth/strategy_spec.rb:659:in `block (4 levels) in <top (required)>'
```

Looking at the [changelog](https://github.com/rack/rack/blob/master/CHANGELOG.md), it looks like these minor version bumps had some changes, were they intended to be breaking?

**Comment by jeremyevans** [comment]
We tightened various areas of the SPEC.  Your first error is probably because you are expecting a the last element of the rack response array to be a `Rack::Response`, and now a plain array is used.  That is a bug in the test, it should only rely on the fact that the last element of the rack response array responds to `each` and yields strings.

The second error is probably related to the host/hostname changes.  I think that may also be expected.  If you post the code, @ioquatix should probably be able to see if the breakage is expected.

**Comment by jeremyevans** [comment]
Looking at the second error, I think that is also expected.  `HTTP_HOST` should contain the port if the port is nonstandard.  Your test doesn't do that, which is a bug in the test.  This also affected one of my libraries: https://github.com/jeremyevans/roda/commit/6b10d73d38b04852883fbcfb1d5ccb36fd97f998

Since both of the breakages are due to bugs in your tests, I'm going to close this.

**Comment by ioquatix** [comment]
Thanks @jeremyevans for the quick follow up!

**Comment by BobbyMcWho** [comment]
@jeremyevans is there a reason you need to include the port in HTTP_HOST when a separate SERVER_PORT opt is passed as well?

**Comment by matthewd** [comment]
Like the other `HTTP_*` entries, `HTTP_HOST` is the HTTP `Host` header value. And that header's behaviour is well-defined -- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Host:

> If no port is given, the default port for the service requested (e.g., "80" for an HTTP URL) is implied.

(that page does link to [the relevant RFC section](https://tools.ietf.org/html/rfc7230#section-5.4) too -- I'm just using it because it has a less opaque wording)

**Comment by BobbyMcWho** [comment]
@jeremyevans Looking at this again, the fact that a plain array is used as the last element vs a rack response, that by definition is a breaking change, no?

**Comment by ioquatix** [comment]
You were relying on undefined behaviour. The last element is only required to respond to `#each`

**Comment by BobbyMcWho** [comment]
Thanks @ioquatix , I apologize for the noise, I just recently started maintaining omniauth and am ensuring I do what due diligence I can before simply changing those existing specs willy-nilly with what a wide footprint omniauth has.

**Comment by ioquatix** [comment]
Let me know if I can help in any way.
