### ISSUE TITLE
Rack::ContentLength and net/http issue

### ISSUE THREAD

**Issue by jmreid** [rack/rack#1615]
It appears that Ruby's net/http leaves behind an incorrect `content-length` header when it fetches and inflates a compressed object:
https://bugs.ruby-lang.org/issues/16672

Rack changed the behaviour in 2.0.8 to no longer compute the content-length on each body  write (https://github.com/rack/rack/issues/1472#issuecomment-574362342) and instead use `Rack::ContentLength` if you need to compute the content-length.

However, `Rack::ContentLength` will not re-compute the length if the `content-length` header exists already.

This means that the incorrect `content-length` is passed back to users and Rack doesn't compute the correct value.

I'm not sure anything needs to change in Rack, to be honest — this feels like a Ruby bug. But I wanted to post here for visibility and any possible discussion if Rack wanted to handle this case in any way. I'm not sure how many other cases of an incorrect `content-length` header being present there might be.

**Comment by jeremyevans** [comment]
I don't think we want to change Rack's behavior in this area.  If a Rack app sets `Content-Length` incorrectly, that is a bug in the app, and the correct response is to fix the app or middleware that is setting the incorrect `Content-Length`.

Having `Rack::Response` try to fix incorrect content lengths would impose a significant performance penalty on Rack users are setting `Content-Length` correctly (a vast majority).  Rack's <2.1's behavior of implicitly fixing incorrect `Content-Length` was not by design, it was just an implementation detail.

**Comment by jmreid** [comment]
Agreed @jeremyevans. I'll close this issue here. Hopefully some of these breadcrumbs help the next person who might run into a similar issue.
