### ISSUE TITLE
2.2.3 breaks for cookies with spaces in their names

### ISSUE THREAD

**Issue by granth** [rack/rack#1674]
I think the short answer is, "don't use spaces in your cookie names", but for _historical reasons_ that's something I ran into.

When a cookie with a space in its name is stored, the name is escaped in classic CGI style, with the space (` `) changed to a plus (`+`). In 2.2.2, the plus was unescaped back to a space when the header was parsed. In 2.2.3 that is no longer true (5ccca4722668083732ea2d35c56565fcc25312f8).

This is especially awkward when using `cookies.signed` in Rails. I got around it by copying `cookies[name_with_plus]` to `cookies[name_with_space]` before calling `cookies.signed[name_with_space]` as before.

Anyway, I'm not sure if this is worth fixing. Hopefully this issue will help anyone else who might run into the same thing.

**Comment by fschwahn** [comment]
I'm seeing this issue too - it not only affects cookies with spaces in the name, but also symbols which are escaped, eg. colon:

```ruby
# in controller
cookies.signed["Test::Cookie"] = "ABC"

# later
cookies.signed["Test::Cookie"] # => nil
cookies.signed["Test%3A%3ACookie"] # => "ABC
```

After regressing rack to 2.2.2 it works as expected.

**Comment by jeremyevans** [comment]
This looks like a Rails issue, not a Rack issue. There was a change in Rack 2.2.3 to fix a security issue, and not decoding the cookie names is necessary to fix the security issue.  `cookies.signed` is not part of the Rack API, so I'm guessing the bug is in Rails and should be fixed there.  @tenderlove @eileencodes @matthewd @rafaelfranca any thoughts?

**Comment by granth** [comment]
@jeremyevans The problem surfaced in Rails, but Rack is what actually changed. Bumping the `rack` gem one patch version broke things.

I think the question is whether the change in behaviour I saw is part of the security fix or an inadvertent side effect.

**Comment by jeremyevans** [comment]
It's part of the security fix as far as I can tell.  @tenderlove should be able to confirm.

**Comment by tenderlove** [comment]
Yes, it's part of the security fix. We can't do URI decoding on keys because people can use it to abuse middleware that think they have a secure cookie.  I don't want to revert it because it is a security fix.  I think it would be OK for Rails to encode and decode spaces as a work-around, but I'd rather we don't do any encoding / decoding for these.

I'm really sorry this broke things for you. 🙇🏻‍♂️

**Comment by granth** [comment]
👍 Thanks for confirming!

Yeah, I'm not sure how generally useful having a space/plus special case would be. I'm happy to get rid of it – I added a bit of code to migrate to a key without spaces.

It's a bit of a shame that Rack has lost the symmetry of setting and retrieving cookies with the same key, even for special characters. That's tough to do since `parse_cookies_header` returns a simple hash. I guess Rails could wrap the cookie lookup to use `escape` in the same way as `add_cookie_to_header`.

```ruby
cookies[Rack::Utils.escape(key)]
```

**Comment by grk** [comment]
@tenderlove in this case, would it make sense to also remove the key encoding from cookie writing? After this change, cookie keys are not symmetrical, i.e. if it `escape(key) != key` on writing, it can't be read at all.

**Comment by IanGallacher-AppFolio** [comment]
@tenderlove I'd like to second @grk's question, as I can't to seem to find a response to it answered elsewhere.

I'm trying to understand the logic of the asymmetrical process for storing and retrieving cookies. Shouldn't it both encode and decode, or neither encode or decode the string? Right now cookies with special characters in the cookie names can be stored but not retrieved.

Because we can't safely decode the cookie string without security concerns, is it safe to remove the encoding for special characters?
