### ISSUE TITLE
#fullpath does not take URI fragment into account

### ISSUE THREAD

**Issue by HoneyryderChuck** [rack/rack#1684]
I'm having two issues with using rack in tests, which are interconnected, it seems.

1. Using `Rack::Mock` and redirects with fragment in tests

I'm having an issue [with this particular part of the code](https://github.com/rack/rack/blob/master/lib/rack/mock.rb#L114), as `QUERY_STRING` never takes the fragment of a given URI into account. This is a problem because [capybara by default follows redirects](https://github.com/teamcapybara/capybara/blob/master/lib/capybara/rack_test/browser.rb#L49-L55), which will call `Rack::MockRequest.env_for` recursively, which will meanwhile "erase" any fragment from the redirect URI.

I've worked around this problem by adding this patch:

```ruby
def env_for(uri, _)
  env = super
  env["QUERY_STRING"] = "##{uri.fragment}" if uri.fragment
  env
end
```

This patch now leads to the second problem:

2. Rack::Request#fullpath not taking fragments into account

As stated, my workaround was effectively appending the fragment into the query string. However, because the implementation of `Rack::Request#fullpath` prepends **always** a "?" when having a query string, this poses a problem if the  query string would be "#state=STATE", which translates to "?#state=STATE" from `#fullpath`, which, although not invalid, is definitely not idea(?).

---------

Supporting fragments is necessary for testing implementations of OAuth interactions which use fragments.

**Comment by jeremyevans** [comment]
In regards to `Rack::Mock`, can you put together a self contained example that doesn't use capybara that shows what the problem is?  It seems like taking the redirect response and looking at the Location header would show the entire URL, including the fragment.  If capybara is not considering the fragment in a way that is affecting your testing, maybe that is a capybara issue?

In regards to `Rack::Request#fullpath`, I'm not sure on a normal request it could take a fragment into account, since fragments are not sent in the request.  If you put http://foo.com/bar#baz into a browser, the #baz part is never sent to the server.

**Comment by HoneyryderChuck** [comment]
The simplest example is:

```ruby
Rack::MockRequest.env_for("https://example.com#state=STATE")
```

where the returning env overlooks the fragment.

I don't think this self-contained example tells the whole story without the capybara context, which "acts as a browser", so given this, do you think this is more of a capybara issue than a rack issue?

>  I'm not sure on a normal request it could take a fragment into account, 

I guess that, given what was said above, unless rack request is supposed to represent a redirected request, it's a non-issue(?).

**Comment by jeremyevans** [comment]
I'm not sure how the returned env should handle the fragment other than ignoring it, as in a regular request, the server would not have access to the fragment.  So this does seem to be more of a capybara issue than a rack one, since capybara is supposed to be operating as a browser-simulator, and fragments in URIs are only handled by the browser.

So, given this discussion, do you think this can be closed?

**Comment by HoneyryderChuck** [comment]
Yup, I do. Thx for the support!
