### ISSUE TITLE
Rack is vulnerable to integer overflow vulnerability in range filter module resulting into leak of potentially sensitive information triggered by specially crafted request.

### ISSUE THREAD

**Issue by satyasys** [rack/rack#1708]
Hello,

An issue initially reported for NGINX is happening even in rack server

You need to run
python CVE_2017_7529.py https://domain/favicon.ico
to reproduce the same, script is available at
https://gist.github.com/thehappydinoa/bc3278aea845b4f578362e9363c51115

This vulnerability has been confirmed by BAT team in Hackeone
https://publishers.basicattentiontoken.org/favicon.ico

**Comment by ioquatix** [comment]
What rack server are you referring to?

**Comment by satyasys** [comment]
The original CVE was reported for nginx, but with publishers.basicattentiontoken.org we found the issue existed in the latest version of rack. We want to collaborate with you to resolve the bug.
You can get the python script from https://gist.github.com/thehappydinoa/bc3278aea845b4f578362e9363c51115

**Comment by ioquatix** [comment]
Rack is not a server, it's a middleware wrapper which joins servers with applications.

There are several servers:

- Passenger
- Puma
- Falcon
- Unicorn
- Iodine

So, the first thing we need to do, is establish where the issue is. Is it in the Rack middleware which deals with partial responses, or is this something server specific, or is it something application specific (e.g. sinatra, rails, etc).

**Comment by satyasys** [comment]
Rack middleware.

**Comment by ioquatix** [comment]
So something wrong here?

https://github.com/rack/rack/blob/dd22d08d33fe0acc36e971214beddbe6e8d54000/lib/rack/files.rb#L70-L110

**Comment by jeremyevans** [comment]
Rack is pure ruby code.  A true integer overflow vulnerability would be a vulnerability in Ruby itself, since by design Ruby integers do not overflow, they get automatically upgraded from a simple 32/64-bit field to an object that can store integers of arbitrary size. Not saying there isn't a vulnerability here, but an integer overflow seems unlikely.

If this is related to byte ranges, they are parsed here, and it looks safe (calling to_i on the string to get the integer): https://github.com/rack/rack/blob/master/lib/rack/utils.rb#L343

Looking at the script, it submits a request for multiple byte ranges, the second with a very large range end (a little less than 9223372036854776000), and just checks for whether a 206 response is returned with a Content-Range header.  That doesn't test at all for integer overflow, it merely tests for how a server handles a request for a size larger than the size of the file.  Maybe rack returns a response in this case when it shouldn't?  Not sure what the RFC-specified behavior is in that case.  Even if rack should error and not return a response, that seems like a regular bug and not a security vulnerability. Can you explain why you think this is a vulnerability in Rack?

**Comment by satyasys** [comment]
We need to check size and return different code
Please check
http://nginx.org/download/patch.2017.ranges.txt
and
https://mailman.nginx.org/pipermail/nginx-announce/2017/000200.html

**Comment by jeremyevans** [comment]
OK.  So this is a regular bug, not a security vulnerability.  It cannot leak any information that the requester couldn't get anyway by submitting a request for the entire file.  Is that correct?

**Comment by satyasys** [comment]
Quoting ngnix.

"This bug allows an attacker to
obtain a cache file header if a response was returned from cache.
In some configurations a cache file header may contain IP address
of the back end server or other sensitive information"
https://mailman.nginx.org/pipermail/nginx-announce/2017/000200.html

**Comment by jeremyevans** [comment]
I don't think that applies to rack.  Can you confirm that issue with rack and provide a reproducible example?  The code in rack that processes range requests does not use a cache/cache file/cache file header.

**Comment by satyasys** [comment]
1. All servers using rack are vulnerable. This vulnerability has been confirmed by basicattentiontoken team in Hackeone, they could reproduce the issue and resolve it by adding extra filter in their server.
https://publishers.basicattentiontoken.org/favicon.ico

2. We need to add additional check in Rack like
http://nginx.org/download/patch.2017.ranges.txt
to fix the issue

**Comment by jeremyevans** [comment]
It's seems unlikely that all servers using rack are vulnerable, considering that range processing in Rack is only done by Rack::Files, which has to be used manually.  Many servers that use the rack protocol do not even require rack are are completely immune to bugs in the rack library, though applications that run on top of them may use the rack library.

Please back up your claims with an reproducible example that shows a leak of information.  Your links are to favicon.ico files and not to anything showing how another group "confirmed" the vulnerability.

**Comment by satyasys** [comment]
1. Here is the proof and POC, you need to run it on preferably an image
![Rack Defect](https://user-images.githubusercontent.com/48247373/93630521-c7155300-fa07-11ea-9140-003397e53c24.jpeg)

2. Download POC from https://gist.githubusercontent.com/BlackVirusScript/75fae10a037c376555b0ad3f3da1a966/raw/d1cc081053636711881ea45c84e0971d5babe103/CVE-2017-7529.py

3, Run python CVE-2017-7529.py http://rackserver/image or document

4. Rack is not having the additional size check put in the NGINX patch
http://nginx.org/download/patch.2017.ranges.txt

4.

**Comment by jeremyevans** [comment]
I downloaded the POC and installed the many dependencies necessary to run it.  I ran it on using following config.ru file, with one of the favicon.ico files in the same directory:

```
require 'rack'
run Rack::Files.new('.')
```

I used this configuration with unicorn, which runs by default on port 8080:

```
$ unicorn
```

I checked in the browser and a request for http://localhost:8080 correctly shows the favicon.ico.

I then ran the POC with the following result:

```
$python3 CVE-2017-7529.py http://localhost:8080/favicon.ico
[+] localhost:8080 is Vulnerable: TRUE
[i] Receiving Data [2049 bytes] ...
```

The POC sits there continually submitting requests for the file.  From the unicorn log:

```
1963 1963 127.0.0.1 - - [18/Sep/2020:04:38:06 -0700] "GET /favicon.ico HTTP/1.1" 206 4116 0.0042
1963 1963 127.0.0.1 - - [18/Sep/2020:04:38:06 -0700] "GET /favicon.ico HTTP/1.1" 206 4116 0.0043
1963 1963 127.0.0.1 - - [18/Sep/2020:04:38:06 -0700] "GET /favicon.ico HTTP/1.1" 206 4116 0.0042
```

The POC expects that after it has determined the server is vulnerability, it will continually submit requests until it gets data leaked.  However, that never happens in this case, so the loop becomes infinite.  This shows there is no information disclosure vulnerability.

Can you provide a similar example showing a leak and not just the POC incorrectly reporting a vulnerability?

**Comment by satyasys** [comment]
1. When someone is asking for more data than what is available, why 206(partial content) is returned?
2. "This bug allows an attacker to obtain a cache file header if a response was returned from cache." So we need to enable caching to reproduce the problem
3.  Does rack set X-Rack-Cache? Asking, then I can find you vulnerable servers from Shodan

**Comment by jeremyevans** [comment]
1) Rack currently uses 206 for responses for all range requests. RFC 7233 does not appear to specify behavior for requests where the end of the range is beyond the length of the file (https://tools.ietf.org/html/rfc7233#section-4.1).  It only specifies the behavior when the beginning of the range is beyond the end of the file (response status 416).  However, the POC you provided uses an empty range beginning and a very large end.  Rack's behavior of returning all bytes available in the file with the 206 status code appears to be compliant with the RFC.  If I'm missing something, please point out the specific section of the RFC that shows that Rack's behavior is incorrect (which would be a bug and not a security issue).

2) The cache file issue is probably specific to nginx.  "need to enable caching" means nothing in rack, since rack does not include support for proxying to upstream servers and caching their results.  It includes supports for setting headers such as Cache-Control, Etag, Expires, but that is unrelated to the nginx vulnerability.

3) A case insensitive search for X-Rack-Cache in rack's lib directory returns no results.  The header appears to be set by https://github.com/rtomayko/rack-cache, a separate library, which is probably also not vulnerable to the nginx vulnerability.

As far as I understand it, you reported this security issue to another company, and they (probably mistakenly) thought it was a bug in rack, so you reported it here without actually checking and confirming yourself that it affected rack.  Is that an accurate description of the events leading up to filing this issue?

As I've already stated, the type of issue that affected nginx (integer overflow) is very unlikely to happen in a pure-ruby library, since integers in Ruby are not fixed size and do not overflow.

Do you have an POC that shows that rack is actually vulnerable to the nginx issue?  If not, I request that you close this issue.

**Comment by satyasys** [comment]
Come on Rack,

In this case rack/lib/rack/files.rb should return Byte range unsatisfiable

 response = fail(416, "Byte range unsatisfiable") 

I can see the same mistake in Rack that NGNIX fixed it at
http://nginx.org/download/patch.2017.ranges.txt
Why shall I close a valid defect as no defect?

**Comment by jeremyevans** [comment]
From a closer reading of RFC 7233, it appears that Rack's use of 206 is not wrong, and that using 416 in response to the POC would be wrong.  The POC uses two overlapping ranges, the second one having a very large end.  The RFC states in section 3.1:

```
   A server that supports range requests MAY ignore or reject a Range
   header field that consists of more than two overlapping ranges
```

Since it is only two overlapping range requests and not more than two, 206 should be used.  Even if it was more than two overlapping ranges, Rack is allowed to use 206 instead of 416, since the RFC specifies MAY and not MUST.

The RFC in section 2.1 explicitly mentions that byte range requests where the end is greater the length of the file should be treated as until the end of the file:

```
   A client can limit the number of bytes requested without knowing the
   size of the selected representation.  If the last-byte-pos value is
   absent, or if the value is greater than or equal to the current
   length of the representation data, the byte range is interpreted as
   the remainder of the representation (i.e., the server replaces the
   value of last-byte-pos with a value that is one less than the current
   length of the selected representation).
```

So this doesn't even appear to be a bug, let alone a vulnerability.

Come on @satyasys, at least do some basic analysis before reporting a vulnerability.  I'll state again, unless have an POC that shows that rack is actually vulnerable, please close this issue.

**Comment by satyasys** [comment]
So NGNIX fixed it wrongly, there was no vulnerability at the first place?
http://nginx.org/download/patch.2017.ranges.txt
This is bug backlog from 2017, I know, it will be difficult for developer to tell the management that, we have a bug in ruby framework.
Now that this vulnerability is disclosed, it will definitely be misused, defending that will be more difficult.

**Comment by jeremyevans** [comment]
No, NGINX had an information disclosure vulnerability due to integer overflow, since it probably used a 64-bit integer to hold the range end.  The way NGINX fixed the vulnerability may make it slightly out of conformance from the RFC, though.

It appears there is no vulnerability nor bug in rack in this code, so you should probably stop saying this is a bug or vulnerability unless you can show that rack is doing something in violation of the RFC or is actually vulnerable to information disclosure.  For the third time, I ask that you either show rack is vulnerable or doing something wrong, or you close this issue.
