### ISSUE TITLE
Consider enabling a subset of cookie names to be unescaped.

### ISSUE THREAD

**Issue by ioquatix** [rack/rack#1796]
Reviewing https://github.com/rack/rack/commit/1f5763de6a9fe515ff84992b343d63c88104654c I wonder if we can find a better middle-ground.

One option is allow for unescaping of cookie names but only a specific subset of characters that can't be otherwise represented.

Another option is to explicitly disallow unescaping names that start with `__` in any form.

This would largely mitigate the compatibility issue that the security fix introduced i.e. <https://github.com/rack/rack/issues/1674>.

cc @tenderlove

**Comment by IanGallacher-AppFolio** [comment]
I think that's an excellent idea. I'd like to expand on the above proposal.

The way I see it, there are two issues at play here.
1. Encoding & decoding of cookies is asymmetrical. Let's say try to save one of your cookies named after a class in your ruby application, in this case`Foo::Bar`. Although you can set that cookie value using Rack, you will never be able to retrieve that cookie because the cookie name will get decoded as `Foo%3A%3ABar`.

2. If you naively solve for the above using a simple encode/decode, you will have collisions with protected cookie prefixes. For example: `__%48ost-foo` will get decoded as `__Host-foo`. This is [the CVE](https://github.com/advisories/GHSA-j6w9-fv6q-3q52) that we fixed.

I propose we do the following:
1. If a cookie name before decoding does not start with a reserved prefix, but has one after it is decoded, don't decode it.
2. Reduce potential asymmetrical cookie encode & decodes by only encoding & decoding unsafe cookie names, such as `=`. I'm not aware of any issues with `:` as part of a cookie name, do we really need to encode and decode that character?

**Comment by ioquatix** [comment]
Yes, only encoding/decoding a subset of percent-encoded characters can solve this problem, i.e. just don't allow percent encoded `/a-z_/i` which should be totally unnecessary anyway.

**Comment by IanGallacher-AppFolio** [comment]
`/a-zA-Z\-_/` I think covers everything that would be used in a host prefix. That actually might be enough to fix this without needing to check if it uses a host prefix before decoding.

**Comment by ioquatix** [comment]
Nice work @jeremyevans
