### ISSUE TITLE
What do we want to do about `Rack::Utils.byte_ranges`

### ISSUE THREAD

**Issue by ioquatix** [rack/rack#1845]
Based on our discussion of cookie utils methods, do we want to un-deprecate this method?

https://github.com/rack/rack/blob/140db09640a4dfa45a9681f64b93fbbb233ae89b/lib/rack/utils.rb#L359-L365

I'm slightly confused about what we want to do here because it seems like on the one had we are trying to remove methods that depend on the shape of `env` but in other cases we are retaining methods that do exactly that (same for response `headers`).

**Comment by jeremyevans** [comment]
I am in favor on undeprecating the deprecated cookie methods in addition to byte_ranges.

I don't see any future in moving to request and response objects in Rack.  Rack is fundamentally `Hash -> [Integer, Hash, body]`, and I think that is for the best.  I don't want Rack becoming like HTTP, where we switch to a completely different design and just slap a new version number on it.  Fundamentally different protocols/libraries/specs that are not mostly compatible should have different names, not different versions of the same name. 

Future versions of Rack should remain backwards compatible as much as possible with previous versions.  At the very least, it should be possible to write a rack app that will work with every version of the Rack spec.

Consider requiring lower case response headers.  This is the most breaking change in Rack 3, probably the most breaking change ever to the Rack spec.  The only reason I was OK with this is the benefit of doing so is very high, allowing O(1) access to response headers by middleware, preventing the need for middleware to wrap response headers in its own object.  And it is possible to applications to switch to lower-case headers and still be compatible with previous versions of the Rack spec.  With some framework changes to use `Rack::Headers`, this can be almost transparent to application authors.

**Comment by ioquatix** [comment]
I think there is value in trimming some of the excess methods in `Rack::Utils`.

Maybe we can break these up, e.g. `Rack::CookieHelpers` or `Rack::Helpers::Cookies` or `Rack::Utils::Cookie` etc. I don't have a strong opinion but I think it would help reduce complexity and allow us to focus on key areas of responsibility.

For the cookie methods, it's confusing, there are a lot of methods without really good consistency. I am trying to trim these to improve the interface and implementation. But other methods probably need attention.

I think to @tenderlove's point, our goal should not be to require `helper_for_env(env)` but have `helper(env['key'])` so that users are not stuck doing `helper({'key' => value})` just to access some common implementation. An example of this is `byte_ranges` vs `get_byte_ranges` which honestly is really confusing interface.

So it seems like we want:

```ruby
def helper(value)
  # impl
end

def helper_for_env(env)
  helper(env['some_key'])
end
```

I think what @jeremyevans wants is `helper_for_env ` and what @tenderlove wants is `helper`. This applies to request, response, headers, etc.

One of the downsides to having CGI style headers on the input side and HTTP style headers on the output side is the distinct shape of input and output headers impacting our ability to have a shared implementation w.r.t. shared logic. It's probably reasonable to assume there are some helper methods which can handle both request headers and response headers, but because Rack explicitly uses different keys for both, it's hard to make a shared implementation. We should consider this when thinking about `env['rack.request.headers']` which follows the same shape as the response headers.

Perhaps if we agree in general about cleaning this up, maybe we can introduce new methods in `Rack::Helpers::Cookie` (or similar) and leave `Rack::Utils largely alone, but prepare to deprecate the entire set of methods or at least redirect them to specific helpers.

A lot of different directions we could go in, I guess.

**Comment by jeremyevans** [comment]
I'm fine with having both `helper` and `helper_for_env`, as both are useful.  I'm not fine with deprecating `helper_for_env` and keeping `header`, because then you force existing users to switch from:

```ruby
  helper_for_env(env)
```

to

```ruby
  env['foo'] = helper(env['foo'])
```

Which is worse as it is more repetitive (often repeated 3 times as the `env` key used is also a part of the method name).  We should not be forcing existing users to make their code worse when upgrading, for the sole purpose of simpler internals.

I don't think we have any `helper_for_env` without a corresponding `helper`, but if we do, I'm fine adding the corresponding `helper`.  I'm not asking that we add a `helper_for_env` in every case where we have `helper` and such a method would make sense.  I'm only asking that we do not force users to make their code worse by deprecating `helper_for_env` and keeping `helper`.

You have a valid point that we have numerous deprecated cookie methods with non-obvious differences.  I guess the currently deprecated cookie methods can stay deprecated.  Users of `add_cookie_to_header` can switch to `set_cookie_header!`.  We don't need `make_delete_cookie_header` or `add_remove_cookie_to_header` when users can call `delete_cookie_header!`.

I do think it makes sense to undeprecate `byte_ranges`, as `byte_ranges(env, 1000)` is simpler than `get_byte_ranges(env['HTTP_RANGE'], 1000)`.  Forcing users to switch `byte_ranges` to `get_byte_ranges` is requiring that they make their code worse.

**Comment by ioquatix** [comment]
> I do think it makes sense to undeprecate byte_ranges, as byte_ranges(env, 1000) is simpler than get_byte_ranges(env['HTTP_RANGE'], 1000). Forcing users to switch byte_ranges to get_byte_ranges is requiring that they make their code worse.

This is basically the crux of the matter, I do agree with this, but @tenderlove wants to remove it. So we need to get consensus on this and the rest follows naturally I think.

**Comment by jeremyevans** [comment]
OK.  I'll wait for @tenderlove to weigh in. But 2 > 1, so he'll need some help if he wants to keep `byte_ranges` deprecated :)

**Comment by ioquatix** [comment]
I don’t like the name conventions so I think we should try to figure out a standard for it which makes sense.

**Comment by jeremyevans** [comment]
IMO, it's much more important to keep backwards compatibility than to change to the ideal name.

**Comment by ioquatix** [comment]
We can add aliases.

**Comment by jeremyevans** [comment]
That sounds good.  I'm not opposed to adding aliases.
