### ISSUE TITLE
Mock::Response returns empty body when body parts use same buffer object

### ISSUE THREAD

**Issue by aglushkov** [rack/rack#1957]
It is reproduced with rack 2.2 and 3.0.beta1

Reproducing script
```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }
  gem "rack", "3.0.beta1"
  # gem "rack", "2.2.4"
end

class FileIteratorWithBuffer
  def initialize(file)
    @file = file
  end

  def each
    buffer = String.new

    while @file.read(5, buffer)
      yield(buffer)
    end
  end
end

file = StringIO.new('Large large file content')
body = FileIteratorWithBuffer.new(file)

puts "Result: " + Rack::MockResponse.new(200, {}, body).body.inspect

# => Result: ""
```

**Comment by ioquatix** [comment]
If you call `yield(buffer.dup)` does it work as expected?

**Comment by aglushkov** [comment]
yes, Result: "Large large file content"

**Comment by jeremyevans** [comment]
This is because `Rack::MockResponse` uses `Rack::RackResponse#buffered_body!`, which results in iterating over the body that is passed in, and creating a new array with each yielded string.

The weird thing is that `Rack::MockResponse#body` wants to return a string, not an array, so it makes no sense to do a `initial body -> intermediate array-> string` conversion instead of just going directly from `initial body -> string`.  I'll push a possible fix, which passes all specs.

**Comment by aglushkov** [comment]
Thanks a lot :rocket: 

By the way, in Rack::Files this  buffer approach can be used to save long strings allocations https://github.com/rack/rack/blob/main/lib/rack/files.rb#L171-L181

**Comment by aglushkov** [comment]
@jeremyevans Hi, can you reopen this issue? I've update rack version to 3.0.4.2, but provided reproducing script still not work.

**Comment by julik** [comment]
FWIW I have previously flagged this in https://github.com/rack/rack/issues/1722

**Comment by ioquatix** [comment]
@julik Is this still a problem for you?

**Comment by julik** [comment]
Since the answer back then was "wontfix" I worked around it, but it might be that this issue (and the related PR) address my issue too 😄  sorry I wasn't clear. No action required.
