### ISSUE TITLE
Errno::ENAMETOOLONG in multipart parser.

### ISSUE THREAD

**Issue by ioquatix** [rack/rack#1968]
This issue cropped up again in our production environment.

I think you are right, the file name on disk should not be part of the "content type" or any other user supplied data = security risk. Let's have a think about how to deal with this. I like your proposal.

_Originally posted by @ioquatix in https://github.com/rack/rack/issues/1874#issuecomment-1254436186_

**Comment by dentarg** [comment]
Okay, so I too had to rescue `ENAMETOOLONG` in my apps today.

Posting a simple repro to provide some more context for anyone new to this issue.

```ruby
# config.ru
run ->(env) do
  [200, {}, ["params=#{Rack::Request.new(env).params}"]]
end
```
```shell
# This triggers the crash
curl --form 'file=foo;filename=a.'\
'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'\
'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'\
'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'\
'aaaaaaaaaaaaaaaaaaaaaaaa' \
http://127.0.0.1:5000
```

**Comment by dentarg** [comment]
@simi what was your alternative ideas? https://github.com/rack/rack/pull/1874#issuecomment-1110322846

**Comment by dentarg** [comment]
Make Rack return `BadRequest` on anything that causes `ENAMETOOLONG`? (Can't be backported to v2 though, as `BadRequest` doesn't exist there)

**Comment by dentarg** [comment]
> @simi what was your alternative ideas? [#1874 (comment)](https://github.com/rack/rack/pull/1874#issuecomment-1110322846)

Perhaps it was

> If we would like to fix this still in Rack, I would go for random tempfile names and keeping original name around to be able to do checks (mime type?) on that instead of tempfile name.

**Comment by jeremyevans** [comment]
> I think you are right, the file name on disk should not be part of the "content type" or any other user supplied data = security risk. Let's have a think about how to deal with this. I like your proposal.

A random tempfile name may break backwards compatibility in ways that affect production applications.  I'm not sure if switching to a random name gets us more in security than it it loses in backwards compatibility.  I do get the general point about random names being more secure, but can you describe any specific attack vectors from basing the tempfile name on a user provided name?  On a Windows system, I could definitely see it having problems with some characters (raising an exception), but `/`, `\\`, and `\0` are already handled, so at least it shouldn't cause problems on a Linux/Unix system.

I'm fine with adding a limit on filename length (maybe 128 characters?), and only using that many characters if the provided filename goes over that limit.

Note that you can override the default behavior by setting `env['rack.multipart.tempfile_factory']`.

> If we would like to fix this still in Rack, I would go for random tempfile names and keeping original name around to be able to do checks (mime type?) on that instead of tempfile name.

The original name should already be available in the `:filename` entry.  Maybe most callers are using that instead of doing something like `File.basename(params['file'][:tempfile].path)`?

I would guess that most attacks from malicious names will still be present if Rack uses random tempfile names, due to bugs in application code that use the names in ways they shouldn't be used.
