### ISSUE TITLE
Add host validation requirement.

### ISSUE THREAD

**Issue by ioquatix** [rack/rack#1970]
<https://github.com/puma/puma/discussions/2977> for original discussion.

Servers should reject bad requests with invalid host headers.

Invalid means doesn't conform to the syntax described by <https://www.rfc-editor.org/rfc/rfc9110.html#section-7.2> which itself is described by <https://www.rfc-editor.org/rfc/rfc3986#section-3.2.2>.

In theory we can do this in a middleware to ease compatibility.

We need to consider performance impact. Limiting the scope of the validation for performance reasons is acceptable.

cc @MSP-Greg

**Comment by jeremyevans** [comment]
In terms of SPEC, I don't think we should require host validation. I think is better to keep this optional, up to the server.

If you are using a front end web server (e.g. Apache/Nginx), and proxying to a Ruby web server (e.g. Puma/Unicorn), the front end web server will generally perform the host check in order to know which backend web server to route to, in which case a check on the Ruby web server side is redundant.  That's my environment, so this change would not improve security in any of my applications, it would only slow them down.   

If we think validation is important enough to security to require it, it seems odd to limit the validation scope for performance reasons.

SPEC doesn't currently specify the format of any `HTTP_*` values, so doing so for `HTTP_HOST` seems inconsistent.  We don't check that `HTTP_FORWARDED_FOR` is a valid IP or list of IPs, that `HTTP_COOKIE` returns a valid cookie, `HTTP_ACCEPT_ENCODING` and `HTTP_ACCEPT_LANGUAGE` contain valid values, etc.. I understand that `HTTP_HOST` has security issues that other environment keys may not have, though.

I don't think adding this to SPEC will help security, assuming by enforcement that means Lint is doing the check.  In development, you probably aren't getting such attacks, and in production, you aren't using Lint.

I'm positive for shipping a middleware that does this check.  That allows users/frameworks who want to use this support to do so, without negatively affecting users who would not benefit from such checks.

We should be aware when discussing this that just because a host is valid according to the RFC, does not been it is valid for the app.  There are all kinds of host rebinding attacks you can do with valid hostnames, you don't need an invalid hostname for a rebinding attack.  In general, applications should be configured to only accept a specific host or list of hosts if they want to avoid rebinding attacks, assuming they are using the host information in a a way that makes them vulnerable to a rebinding attack in the first place.

**Comment by MSP-Greg** [comment]
As mentioned in the above Puma issue, I was seeing what could be done to minimize performance degradation.

> In general, applications should be configured to only accept a specific host or list of hosts

But, the best place to check for the above is in the server, as there's no reason for the request to 'stay alive' if the host is invalid.

So, we may look at adding a config option for valid hosts, and if used, Puma could perform a full validation, and reject the request before it even reads the request body, if included...

**Comment by ioquatix** [comment]
The reason why host validation will fail (according to some definition of hosts/patterns) is **highly** likely to be because of an attack. Stopping this as early as possible has got to be a significant win for security. Doing this in the middleware has already exposed a significant part of the server code to malicious input, so I agree, the earlier this is done, the better. The server is in the best position to prevent these attacks.

**Comment by jeremyevans** [comment]
I agree that it makes sense for the server to prevent such attacks.  As @MSP-Greg mentioned, a server config option for the actual valid hosts for the app seems like the best way to handle this. I don't think it's worth specifying in rack.

**Comment by ioquatix** [comment]
I think we should consider adding options like:

``` ruby
# config.ru

# Should we consider server agnostic options/configurations?
option :allowed_hosts, ["myhost.com"]
```

**Comment by tenderlove** [comment]
I agree this shouldn't be part of SPEC.  Unsure if we should add support for this in the `rackup` world.  If we did that, it would mean that the RU file would become not portable between webservers (or not make sense given a particular webserver).

**Comment by ioquatix** [comment]
> If we did that, it would mean that the RU file would become not portable between webservers (or not make sense given a particular webserver).

I don't understand, the entire point is to have a generic configuration rather than having to write the same config for N different servers, e.g. `config/puma.rb`, `config/falcon.rb` `config/unicorn.rb`.

You are right, severs would need to support it, but that's true no matter what.

We could do it as a middleware, but that has a different set of trade offs - adoption - too late to block the attack completely - etc.

**Comment by dentarg** [comment]
This protection/validation exists in Rails as the [`HostAuthorization` middleware](https://github.com/rails/rails/blob/v7.1.3.3/actionpack/lib/action_dispatch/middleware/host_authorization.rb) ([docs](https://guides.rubyonrails.org/configuring.html#actiondispatch-hostauthorization), [past security issues](https://groups.google.com/g/rubyonrails-security/search?q=Open%20Redirect)). Are we talking about adding the same to either Rack or Puma (and other servers?). Adding it to Rack seems optimal, as that is the single piece of infrastructure everyone uses.

**Comment by ioquatix** [comment]
Yes, my proposal is we should validate the host header. However, I think there are good reasons why it shouldn't be done too.

I suppose the question should be, if we did implement it in Rack as an optional feature, would anyone actually opt out?

**Comment by jeremyevans** [comment]
I'm against adding support for this by default as I would prefer it be left up to servers.  I'm strongly against adding this to SPEC.  I'm open to shipping a middleware if we want to support this.

**Comment by ioquatix** [comment]
Understood. I'll consider whether shipping a middleware makes sense.
