### ISSUE TITLE
InputWrapper should delegate to original input any methods that it does not support directly

### ISSUE THREAD

**Issue by aglushkov** [rack/rack#1973]
From discussions https://github.com/rack/rack/discussions/1972

So if original input has `#rewind` method, then it should be possible to call it from InputWrapper

**Comment by jeremyevans** [comment]
I'm not sure we want to do this.  `Lint` is checking that the app's use of the input is within the rack API and should be portable to other webservers supporting the rack API.  If we start allowing `Lint` to delegate all input methods, code that passes `Lint` on one webserver could fail on another webserver.

In Rack 3, you can use the `Rack::RewindableInput::Middleware` in the middleware chain after `Rack::Lint`, ensuring that the input is rewindable, even if the webserver does not provide rewindable input.

**Comment by aglushkov** [comment]
Rewindable middleware is too much if you want to rewind inputs of 1% of  requests (when error happens for example). I don't want additional 1000 disc writes to track request body of single error request, knowing that original input already supports `#rewind`. 

Maybe rack can expose @input instance variable whatever it is? Just adding `attr_reader :input` to that Lint. So rack will be not responsible what app is doing with it?

**Comment by jeremyevans** [comment]
You cannot only rewind on error.  If you don't support rewindable input before the input is read, if there is an error after reading input, there is no ability to rewind the input if an error happens.

In terms of `RewindableInput::Middleware`, we could change that to not wrap the input if the input already rewindable.  However, the idea is that you should only use the middleware if you know the input is not going to be rewindable and you need it to be rewindable.

Since your issue appears to be specifically with `Lint`, I would recommend just not using `Lint`, or creating a subclass of `Lint` with your desired changes, and using that.  `Lint` is not designed to solve any problems, only to alert you to potential problems you have.

**Comment by aglushkov** [comment]
> I would recommend just not using Lint

Thanks a lot for this notice, really) 
There are no docs (or I can't dind them) how to enable/disable Lint, I thought it can not be disabled.

It turns out it is enabled by default with Rackup, and can be disabled with `rackup --env none`.

Now issue is gone for me)
