### ISSUE TITLE
Flaky JRuby tests.

### ISSUE THREAD

**Issue by ioquatix** [rack/rack#2027]
https://github.com/rack/rack/actions/runs/3992070873/jobs/6847563270#step:4:121

<img width="641" alt="image" src="https://user-images.githubusercontent.com/30030/214252438-e455417b-8b42-4cfb-88b2-4a579b7e7078.png">

**Comment by headius** [comment]
Has this happened again? Whatever caused it may have been fixed after 9.4.0.0.

**Comment by headius** [comment]
These tests seem to be generated... how do I determine what test is actually triggering this?

**Comment by headius** [comment]
Ah nevermind, is that some weird naming generated by the test harness? I believe this is the test in question??

https://github.com/rack/rack/blob/1fc01e1443e6dc14ba14720df4c774f89d706b5a/test/spec_deflater.rb#L313

**Comment by ioquatix** [comment]
I suppose what might be a concern is it looks like some kind of off-by-1 error...? So it might be data corruption bug.

**Comment by headius** [comment]
My guess is something related to rounding in time conversions.

I believe these numbers are the modification time in epoch seconds, derived from a Time.httpdate.to_i for the expected value and a Time.httpdate passed through our Java-based zlib's mtime header in the actual value.

When I loop the spec 1000 times, it will fail roughly half the time, and pass half the time. Adding some logging and allowing it to run, you can see it change at whole-second and half-second boundaries.

Here it goes from failing to passing at the whole second boundary (rational here is Time.now.subsec, equality check is [last_modified mtime] vs [zlib mtime]):

```
499711/500000
Thu, 25 May 2023 12:58:28 GMT
1685019508 != 1685019509
249947/250000
Thu, 25 May 2023 12:58:28 GMT
1685019508 != 1685019509
153/1000000
Thu, 25 May 2023 12:58:29 GMT
1685019509 == 1685019509
263/500000
Thu, 25 May 2023 12:58:29 GMT
1685019509 == 1685019509
913/1000000
Thu, 25 May 2023 12:58:29 GMT
```

And here going from passing to failing at a half-second boundary:

```
499177/1000000
Thu, 25 May 2023 13:00:27 GMT
1685019627 == 1685019627
249777/500000
Thu, 25 May 2023 13:00:27 GMT
1685019627 == 1685019627
500013/1000000
Thu, 25 May 2023 13:00:27 GMT
1685019627 != 1685019628
250207/500000
Thu, 25 May 2023 13:00:27 GMT
1685019627 != 1685019628
```

This could be avoided in the spec by always using a specific HTTP date/time rather than using the current time, but I guess there's still something to be fixed here.

Perhaps our mtime logic in zlib is tacking on some subsec to the mtime when putting it into the zip headers, which leads to it rounding one way or the other when it comes out the other end.

**Comment by ioquatix** [comment]
Awesome!

**Comment by ioquatix** [comment]
As this is not an issue with Rack, I'm going to close it.
