### ISSUE TITLE
Rack 3 post install message (changelog)?

### ISSUE THREAD

**Issue by zzak** [rack/rack#2036]
Was chatting with @ioquatix and we talked about adding a warning when users upgrade to Rack 3, that will link them to the release notes explaining there are break changes that might affect your application.

Currently when a user upgrades to actionpack 7.1.0.alpha, the upper-bound dependency on rack (`~> 2.0`) will be removed. This means, if the user runs `bundle update` or similar, they could get Rack 3 by accident.

A quick search turned up [#post_install_message](https://guides.rubygems.org/specification-reference/#post_install_message), but perhaps there are alternatives?

**Comment by jeremyevans** [comment]
I abhor gem post install messages.  I think the vast majority of users understand that a major version bump can mean breaking changes, especially those users that are running prerelease versions of gems such as actionpack 7.1.0.alpha.  As a point of reference, I don't think Rails itself uses post install messages, even though they have breaking changes every major version.

**Comment by ioquatix** [comment]
> I think the vast majority of users understand that a major version bump can mean breaking changes

I'm not so sure about that, it assumes that (1) people realise `bundle update` is updating a major version and (2) they see it.

It would be nice if we could emit a message only in the case that they are updating a major version.

**Comment by MSP-Greg** [comment]
> It would be nice if we could emit a message only in the case that they are updating a major version.

Agree in principle, but how would one determine "in the case that they are updating a major version"?

Two items:

1) I abhor gem post install messages => post install messages are a nuisance => I ignore post install messages (especially RubyGems)

2) How many Rails users actually write code against Rack objects?  They expect Rack, Rails and their web/app server to all work together.

**Comment by matthewd** [comment]
Personally I don't think that, strictly speaking, Rails main should currently be allowing Rack 3, because it's not compatible, but we've chosen to do so to make it easier to progressively step over the various compatibility issues in separated PRs.

Outside of that special circumstance (where our unreleased main branch is knowingly allowing a gem version that we ourselves are incompatible with), I think it's fine to expect that if an application is going to have an issue, some other dependency will handle it: if they're directly depending on Rack behaviour, they should have an appropriately-constrained Gemfile entry; if they have some other Rack-using dependency, that gem will itself have suitable constraints.

If an application is only interacting with Rack via Rails, then no Rack version change should cause any breaking change for them, and any message to the contrary would be misleading.

Beyond Rails not using them itself, no Rails dependency, direct or indirect, has a post install message.

**Comment by ioquatix** [comment]
This is probably a separate discussion, but tangentially related, but is there some kind of migration guide for users of Rails? Maybe this would be a good place for such a discussion.

**Comment by tenderlove** [comment]
I agree with @jeremyevans.  The major version increase should be sufficient to communicate that "things may break".
