### ISSUE TITLE
Rack::Utils.unescape doesn't respect JavaScript's `%uxxxx` notation

### ISSUE THREAD

**Issue by boazsegev** [rack/rack#2119]
JavaScript uses a `%uxxxx` notation to escape unicode data when performing percent encoding.

This may be non-standard, but it is in the wild (try it on Chrome / Safari and see):

```js
console.log(unescape("%u05E9%u05DC%u05D5%u05DD")); // => "שלום"
console.log(escape(unescape("%u05E9%u05DC%u05D5%u05DD")) == "%u05E9%u05DC%u05D5%u05DD"); // => true
```

With Rack, one would expect:

```ruby
Rack::Utils.unescape("%u05E9%u05DC%u05D5%u05DD").force_encoding("UTF-8") # => "שלום"
```

But one gets:

```ruby
Rack::Utils.unescape("%u05E9%u05DC%u05D5%u05DD").force_encoding("UTF-8")
# => invalid %-encoding (%u05E9%u05DC%u05D5%u05DD) (ArgumentError)
```

I believe this is a bug because, although non-standard, one expects Rack to handle browser JavaScript output correctly.

**Comment by jeremyevans** [comment]
`Rack::Utils.unescape` is for unescaping URI-escaped strings (according to the documentation), not for unescaping JavaScript escapes, so I don't think this is a bug.  If you are using `Rack::Utils.unescape` for unescaping JavaScript, you are misusing the API, IMO.

**Comment by boazsegev** [comment]
As you wish, obviously.

However, consider a URI authored by a JavaScript client, what would be the expected behavior at that point?

IMHO, there is a case for supporting the `%uxxxx` format.

**Comment by jeremyevans** [comment]
The expected behavior is the JavaScript client would use URI escapes in their URIs, and not JavaScript escapes, as JavaScript escapes are not valid in URIs.  Which JavaScript URI library is creating URIs containing JavaScript escapes instead of URI escapes?

Note that introducing JavaScript unescaping would open up possible security issues resulting from different unescaping by application code compared to possible proxy servers and web application firewalls.

**Comment by boazsegev** [comment]
Since `%` should be escaped (`%25`), `%uxxxx` would not be a valid application code sequence (that would be `%25uxxxx`).

However, I will close this issue considering this is not my call.

If you do decide to allow for less well-coded clients, feel free to re-open.
