### ISSUE TITLE
Thin handler calls the wrong class to parse options

### ISSUE THREAD

**Issue by TikiTDO** [rack/rack#745]
Affected File: https://github.com/rack/rack/blob/master/lib/rack/handler/thin.rb#L17

The Thin handler creates a ::Thin::Server instance, however in thin the class responsible for parsing most of the user options is ::Thin::Controllers::Controller. This has has created some confusion online since configuring ssl options in the options hash will not work.

Currently to run an SSL server you have to do:

``` ruby
opts = {
  :Port => port,
  :Host => 'localhost'
}
Rack::Handler::Thin.run(app, opts) do |server|
  server.log_file = "example.log"
  server.ssl = true
  server.ssl_options = { 
    :private_key_file => "server.key",
    :cert_chain_file => "server.crt"
  }
end
```

This is a pretty terrible solution as it depends on internal API features of thin.

By using ::Thin::Controllers::Controller instead of ::Thin::Server this can be changed to:

``` ruby
opts = {
  :Port => port,
  :Host => 'localhost',
  :log => "example.log",
  :ssl => true,
  :ssl_key_file => "server.key",
  :ssl_cert_file=> "server.crt"
}
Rack::Handler::Thin.run(app, opts)
```

Which is more in line with how the better documented webrick behaves.

If this is not a viable solution, it would be helpful to at least add a warning in here, since so that people don't go crazy trying to pass in ignored options .

**Comment by jeremyevans** [comment]
This change seems reasonable to me.  Thin::Controllers::Controller seems supported since Thin 0.7.0, and I'm sure we don't care about supporting anything older than that.

The only issue with this is that Thin::Controllers::Controller doesn't accept a block, so we'd still need to keep the current approach if a block is passed.  I don't think doing that is a problem though.

I'll submit a pull request for this.
