### ISSUE TITLE
Rack::Utils.build_nested_query should use escaped square brackets

### ISSUE THREAD

**Issue by hkmaly** [rack/rack#792]
According to validator.w3.org and http://www.ietf.org/rfc/rfc3986.txt square brackets are not valid characters in query part of url and should be escaped as %5B resp %5D.

Rack::Utils.build_nested_query is using unescaped ones.

I must admit I'm not entirely sure what is you supposed to do if you want to use square brackets as hash key, but seems that input part of rack is already parsing encoded square brackets according to http://www.ietf.org/rfc/rfc3986.txt ...

**Comment by mcantor** [comment]
Can you be a little more specific about what you mean by "input part of rack"?

**Comment by mig-hub** [comment]
For reference, I pulled paragraphs talking about this.

> IPv6 (and later) literals have been added to the list of possible
   identifiers for the host portion of an authority component, as
   described by [RFC2732], with the addition of "[" and "]" to the
   reserved set and a version flag to anticipate future versions of IP
   literals.  Square brackets are now specified as reserved within the
   authority component and are not allowed outside their use as
   delimiters for an IP literal within host.  In order to make this
   change without changing the technical definition of the path, query,
   and fragment components, those rules were redefined to directly
   specify the characters allowed.

And this one.

> A host identified by an Internet Protocol literal address, version 6
   [RFC3513] or later, is distinguished by enclosing the IP literal
   within square brackets ("[" and "]").  This is the only place where
   square bracket characters are allowed in the URI syntax.  In
   anticipation of future, as-yet-undefined IP literal address formats,
   an implementation may use an optional version flag to indicate such a
   format explicitly rather than rely on heuristic determination.

**Comment by hkmaly** [comment]
By "input part" I mean whatever is parsing the request. Utils.parse_nested_query probably, although I don't see anything there which would seem related, so it may be sideefect of something.

What I wanted to say is that I tried to change the links to be valid according to the RFC and it worked.

**Comment by jeremyevans** [comment]
RFC 3986 does indicate that `[` and `]` should not appear in query strings, as they are gen-delims and not sub-delims. I think it makes sense to escape them. I'll submit a pull request for it, but I'll definitely want another core team member to review and determine if we want to make this change.

**Comment by ioquatix** [comment]
>  All browsers I tested escape [ and ] when submitting requests per the RFC. Firefox displays the unescaped version in the address bar, but submits the escaped version. (@jeremyevans)

I think the consensus here is that we won't implement this as it would make URLs even more unreadable and the informal standard is that they are acceptable.

If you think this isn't a good position for `rack`, please feel free to discuss it. At least one way to deal with this would be to make it optional when generating query strings.

**Comment by tenderlove** [comment]
Sorry, this ship has sailed.  We're not following the RFC and things seem to be working.  If we changed the code to follow the RFC, then yes we would be more "technically correct", but on the other hand we'd probably end up breaking a ton of code and with no benefit to us or Rack users.
