### ISSUE TITLE
What if the encoding is more than one?

### ISSUE THREAD

**Issue by luctus** [rack/rack#924]
The "Accept Encoding" that I see in my browser is "gzip, deflate, sdch" and I see [here](https://github.com/rack/rack/blob/master/lib/rack/deflater.rb#L60) that we have a ```case encoding```, so it will go to the first ```when``` (gzip) and it will ignore the "deflate" part of the encoding.

This is a screenshot of my Request Headers:
<img width="598" alt="screen shot 2015-08-13 at 12 32 57 pm" src="https://cloud.githubusercontent.com/assets/365101/9254014/7df44f9a-41b7-11e5-97ce-f868c8f632ff.png">

Am I missing something?

The point is that with a ```gzip, deflate``` encoding I'm expecting to receive a "deflated AND compressed" response

**Comment by mig-hub** [comment]
I see what you mean but when I read [this document](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html), it seems to me that the encodings are not meant to be cumulative.

The behaviour of `Rack::Utils.select_best_encoding` seems to do what this quote suggests:

> If multiple content-codings are acceptable, then the acceptable content-coding with the highest non-zero qvalue is preferred.

I am not sure if this is still true when there is no `q` value, but I don't see why it would be different. The fact that there is a `q` value actually sort of implies that there can't be more than one, otherwise you would not have to rate then.

I may be wrong because I am not very good at reading spec documents, but this is how I understand it.

**Comment by matthewd** [comment]
Yeah...

> The point is that with a `gzip, deflate` encoding I'm expecting to receive a "deflated AND compressed" response

I can't speak to what you expect, but I am quite sure your browser is *not* expecting that.

**Comment by luctus** [comment]
Thank you very much @mig-hub and @matthewd for your responses. It's clear now.
