### ISSUE TITLE
Stop setting HTTP_VERSION to SERVER_PROTOCOL

### ISSUE THREAD

**Issue by mattrobenolt** [rack/rack#970]
I'm opening this to discuss the merits and reasonings for setting HTTP_VERSION inside of the different rack handlers.

See my "Notes" under #969 for a little bit of context.

tl;dr is in all of the handlers, rack does this little bit:

``` ruby
env[HTTP_VERSION] ||= env[SERVER_PROTOCOL]
```

This causes an environment variable to get set to for `HTTP_VERSION`, when according to the CGI spec, `HTTP_*` is explicitly reserved for client headers. This makes it confusing if something downstream is attempting to collect all client headers, this becomes ambiguous. Did the client sent a `Version` header? Or is this the `Version` header that Rack is declaring?

This behavior is wrong, but I'm not sure of the ramification of simply... stopping doing this. I can't seem to find things that reference this, except the internals that were fixed up in #969, but no idea how common this is downstream to actually use this value.

**Comment by ioquatix** [comment]
I don't do this in `falcon` and I haven't had any complaints.

**Comment by jeremyevans** [comment]
Rack is still setting `HTTP_VERSION` in the environment in all handlers.  Unicorn sets it and ignores any `Version` request header submitted.  I'm guessing there are some middleware that are relying on `HTTP_VERSION` instead of using `SERVER_PROTOCOL`.  So this becomes a case of whether the backwards compatibility breakage is worth adding support for the `Version` request header.  I don't have a strong opinion on that, but I would lean toward keeping backwards compatibility.

**Comment by ioquatix** [comment]
Moving this to v3.0.0 milestone.

**Comment by tenderlove** [comment]
IMO it's fine to remove this for v3.0.0
